### ISSUE TITLE
create_voucher does not return a voucher code

### ISSUE THREAD

**Issue by zone11** [Art-of-WiFi/UniFi-API-client#1]
I'm creating a new voucher using create_voucher and the response only contains the creation date but no voucher code.
Tested using unifi-api-client v1.1.16 and Unifi Controller 5.5.20

Debug Output:
```
-------URL & PAYLOAD---------
https://192.168.254.10:8443/api/s/default/cmd/hotspot
json={"cmd":"create-voucher","expire":4320,"n":1,"quota":0,"note":"Buttonprinter: 2017.10.09"}
----------RESPONSE-----------
{ "data" : [ { "create_time" : 1507562169}] , "meta" : { "rc" : "ok"}}
-----------------------------
```

**Comment by malle-pietje** [comment]
That's correct, this is behavior that recently changed:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L921

If you wish to get the newly created vouchers you can immediately call this function with that timestamp as the parameter:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L848-L864

**Comment by malle-pietje** [comment]
Here's the comment in the code suggesting exactly this:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L931

**Comment by zone11** [comment]
I'm sorry, missed that one...
Just upgraded from the "old class" without further checks.

**Comment by malle-pietje** [comment]
No problem.
