### ISSUE TITLE
Updates to new API versions

### ISSUE THREAD

**Issue by galvesribeiro** [Art-of-WiFi/UniFi-API-client#109]
Hello!

Just curious, how are you keeping those APIs updated when there is a new version of the controller? Is there a Swagger spec on the controller or somewhere Ubiquiti publishes all the APIs? 

Thanks!

**Comment by malle-pietje** [comment]
No swagger available I’m afraid. Besides that, a swagger file is unable to deal with the specific login process, especially with the detection of UniFi OS devices.

It’s mainly a matter of community effort in testing and sharing any changes that get identified.

**Comment by galvesribeiro** [comment]
Understood... 

I'm working on create an OSS platform that would basically do what Unifi Cloud is supposed todo but that people can deploy privately and don't need any of the Unifi crap. For that to work, either I can use the API or implement things by using the CLI.

The thing is that both the CLI and the API are not documented anywhere :/ 

The project will live on this org https://github.com/Unifi-Tools along other tools that are in the works.

I'll investigate more to see whether there is something we can use to re-generate the API (just like we do with swagger) so it make our lives easier. It would be quite hard to keep those methods up-to-date without something like this...

**Comment by malle-pietje** [comment]
Interesting. I’ll keep an eye on that. I totally agree with your last remarks. Swagger would make life a lot easier...
