### ISSUE TITLE
Statistics returning 0 in 6.1.71

### ISSUE THREAD

**Issue by alfo** [Art-of-WiFi/UniFi-API-client#112]
The following two API calls have started to report 0 for `wan-tx_bytes` and `wan-rx_bytes` on all days at all times, despite the fact that devices on my network are definitely still communicating with the internet:

```
$unifi_connection->stat_5minutes_site();
$unifi_connection->stat_daily_site();
```

This is on controller version 6.1.71 on a DMP with firmware 1.9.3. Any tips to get these working again?

**Comment by malle-pietje** [comment]
I'm afraid I don't have a UDM PRO with a live site behind here to test. Have you checked with the API Browser tool to see what it returns?
