### ISSUE TITLE
one controller - 2 sites

### ISSUE THREAD

**Issue by christianguei** [Art-of-WiFi/UniFi-API-client#117]
Hello,

Thanks for you awesome library again.
I've a quick question for you, is it possible to use the same devices on 2 sites located physically at the same place ?

Site 1 : usg pro4, switch, 3 ap
Site 2 : same devices

In order to manage 2 wifi hotspot configuration (coupon)
Thanks

**Comment by malle-pietje** [comment]
You’re welcome! No, a UniFi device can only be managed within a single site. The only (messy) approach would be  to spread the APs across two sites. Each AP will broadcast its SSIDs with the associated Guest Controls. Does mean you need almost 2x the APs and you create a lot of extra RF noise.

**Comment by christianguei** [comment]
Ok i see i've just managed to setup the second "site" and adopt an AP.

I've also set a coupon based auth for 2nd site but cannot go to hotspot manager, it always bring me back to the login page :( Do you have a solution ?

**Comment by malle-pietje** [comment]
I’m afraid this is outside of the scope of this repo. I know there are quite a lot of people with similar issues so I recommend you search the Ubiquiti forums.
