### ISSUE TITLE
x_passphrase field missing from response

### ISSUE THREAD

**Issue by NickDunas** [Art-of-WiFi/UniFi-API-client#129]
I noticed that the x_passphrase is missing from the response I get from our controllers. I contacted ubiquity help center, but they cannot help me. I see that passphrase does exist on the responses on UniFi API Browser demo. Any ideas what I might be doing wrong?

**Comment by malle-pietje** [comment]
OK, that code looks fine. Yes, installing the API browser will be useful anyways and give you fast and easy access to most of the API endpoints.

In the output you get do you see a value for the `wpa_mode` key?

**Comment by malle-pietje** [comment]
Ok, in that case I suspect it’s a controller related issue. Which version are you running? Please also confirm what the output from the API Browser tool is, and please check as many sites and controllers as possible.
