### ISSUE TITLE
How to create a site?

### ISSUE THREAD

**Issue by reillychase** [Art-of-WiFi/UniFi-API-client#14]
Cool API library thanks!

Do you have an API call to create a site? 

An API call to create a user for a site?

**Comment by malle-pietje** [comment]
Create a site, yes:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L861

Assign a user to a site, not yet.

**Comment by reillychase** [comment]
Nice work, thanks!

**Comment by malle-pietje** [comment]
Thanks, you’re welcome!

**Comment by reillychase** [comment]
Nice! Very clean code. Yes that covers it. You might note that this also covers re-inviting an admin, you can simply call the invite-admin function again to send a second invite email. 

I actually ended up writing my program in Python but your library was a big help in understanding the API.

**Comment by malle-pietje** [comment]
Thanks for the feedback. Will add that remark regarding re-invite to the comments.
