### ISSUE TITLE
ap_upgrade_firmware.php causes firmware downgrade

### ISSUE THREAD

**Issue by 4oo4** [Art-of-WiFi/UniFi-API-client#15]
Finally got a chance to put this to the test, and for some reason it ended up downgrading the firmware, even though it was already on the latest, since it must have just seen that there was a different version available and ran with that.

I'm hoping there are separate API calls for upgrade/downgrade to prevent this from happening? The frustrating thing is that I can't seem to get it to find the latest firmware again, so I'll have to reinstall that manually. I'll also see if anyone has any suggestions on the Ubiquiti forums.

**Comment by malle-pietje** [comment]
Did you make a note of the firmware versions before and after?
If you’re running a recent controller you may have experienced the conquences of UBNT pulling 3.9.24 and making 3.9.21 the current release again. This forces devices to “upgrade” down to 3.9.21 if they are at a higher release.

**Comment by 4oo4** [comment]
Yep, those were the exact versions involved. Now that you mention it I think I do remember reading something about them pulling that firmware version, so that actually makes perfect sense. So I guess based on that, this is working as expected. I think I was thrown off that the .24 was still shown as the recommended firmware version in the controller release notes.

I see though that we can query the API to get `upgrade_state` and `upgradeable` for a device, if there are issues like this in the future that are NOT related to them pulling a firmware release, those could be used in the `upgrade_device` function to ensure the release is actually newer.

**Comment by malle-pietje** [comment]
Indeed, these can be used in your custom code.
