### ISSUE TITLE
External portal : iOS user keeps the portal window open instead of validating connexion

### ISSUE THREAD

**Issue by ronan-paul** [Art-of-WiFi/UniFi-API-client#161]
Hello

We have set an external portal using UniFi-API-client. 

A popup window opens automatically on our external portal when the user connects to the WiFi for the 1st time, and we authorize the mac address after a successul login on our portal. 
But the popup window remains open for some peripherals. 

For example:
1 - on iOS the popup stays open, which apparently means that iOS does not consider the connexion completed. And the user can click on the "cancel" button of the popup, which closes the WiFi connexion (see screenshot)
![image](https://user-images.githubusercontent.com/7871756/171458903-4577bbe0-aca9-4993-81b7-5f3082c85404.png)
The event log shows seems OK: 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/7871756/171459937-2c99172a-67b3-48a0-bb4b-4374ce631d0d.png">

2 - on macOS, I also get the same problem:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/7871756/171459431-772a1ad6-7538-434a-a919-85b93145cd27.png">
The event log shows that everything is OK: 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/7871756/171459763-1679f2a1-aa94-4b73-96ee-d083cc9f1b78.png">

=> Am I missing something ? What should I do so that the connexion is considered as complete by the client computer ? 

Regards,

Ronan

**Comment by malle-pietje** [comment]
From what I see the API client is working fine (as confirmed by the event log) which means something else isn’t working as it should. I’m afraid that is something I cannot provide support for through this repository; building a stable captive portal solution isn’t always as easy as it seems.
