### ISSUE TITLE
Invalid Url Response

### ISSUE THREAD

**Issue by julius-gitonga** [Art-of-WiFi/UniFi-API-client#162]
I get this response when i make a call to the client

<b>Notice</b>:  The URL provided is incomplete, invalid or ends with a / character! in <b>/var/www/one/dev3/vendor/art-of-wifi/unifi-api-client/src/Client.php</b> on line <b>3786</b><br />

The url passed is in the format 'https://192.XXX.XX.XXX:8443'

**Comment by julius-gitonga** [comment]
I am using Slim 3.0 running on PHP 5.6
//Declaration
  'cloudkey'=>[
            'controlleruser'=>'<username>',
            'controllerpassword'=>'<password>',
            'controllerurl' => 'https://192.XXX.XX.XXX:8443',
            'controllerversion'=>'6.5.55.0'
        ]
//Request function

    public function speedTest(Request $request, Response $response){

        $sid = $request->getParam('id');

        $school=$this->schoolService->fetchSchools($sid);
        $siteid= !empty($school->getSiteid()) ? $school->getSiteid() : 'default';

        $unifi_connection = new Client($this->cloudkey['controlleruser'], $this->cloudkey['controllerpassword'],    $this->cloudkey['controllerurl'], $siteid, $this->cloudkey['controllerversion'], false);
        return $response->withJson($unifi_connection->stat_speedtest_results());
    }

**Comment by malle-pietje** [comment]
Looks fine to me. Please enable debug mode and share the sanitized output from that.

**Comment by malle-pietje** [comment]
Closing due to lack of feedback.
