### ISSUE TITLE
Issues getting it to run

### ISSUE THREAD

**Issue by vivinano** [Art-of-WiFi/UniFi-API-client#163]
Hey I'm unsure what I'm doing I tried to get it working I have the browser version working but wanted to use this one going but seem to be hitting error

Like no http in curl can someone please help ?

**Comment by malle-pietje** [comment]
Please share more details such as your actual code, exact error messages, output with debug enabled, etc.

**Comment by vivinano** [comment]
I fixed it the issue was that I didn't add

The 
HTTPS:// 

When I was configuring my $controllerurl 

Ex: 
I put 192.168.1.1 which gave me a php warning and no results 
But 
Adding the https:// in front of the url resolved these warning and gave me results

**Comment by malle-pietje** [comment]
👍
