### ISSUE TITLE
 Last error message: api.err.UnknownDevice 

### ISSUE THREAD

**Issue by joeladria** [Art-of-WiFi/UniFi-API-client#17]
I'm using locate_ap() and power_cycle_switch_port() and I keep getting api.err.UnknownDevice, it doesn't seem to understand the MAC I'm giving it. I'm using the same format with colon separation, and I'm using the only logical MAC for the switch. Any ideas?

UniFi 5.6.16

**Comment by malle-pietje** [comment]
That's strange, I just ran some tests and cannot reproduce this I'm afraid. This is with a 5.7.23 controller using PHP 7.0.7.

Are you creating the MAC address variables with single quotes or double quotes? Can you also check to see whether the MAC addresses were indeed submitted with the payload and not left blank? You can see this when you enable debug.

This is the code I used to test the locating function:

```php
/**
 * MAC of AP to locate
 */
$ap_mac = "44:88:dd:00:aa:ff";

echo 'strtolower results: ' . strtolower($ap_mac);

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login();
if ($loginresults) {
    $data = $unifi_connection->locate_ap($ap_mac, true);
    //$data = $unifi_connection->locate_ap($ap_mac, false);	
	
	/**
	 * provide feedback in json format
	 */
	echo json_encode($data, JSON_PRETTY_PRINT);
} else {
	echo 'we encountered a login error!';
}
```

**Comment by malle-pietje** [comment]
And here's the code I used to to test the port power cycle:
```php
/**
 * MAC of switch to work with
 */
$switch_mac = "44:d9:e7:11:22:33";

/**
 * index value of port to cycle
 * this must be a port that is actually providing power
 */
$port_idx = 1;

echo 'strtolower results: ' . strtolower($switch_mac);

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login();
if ($loginresults) {
    $data = $unifi_connection->power_cycle_switch_port($switch_mac, $port_idx);
	
    /**
     * provide feedback in json format
     */
    echo json_encode($data, JSON_PRETTY_PRINT);
} else {
    echo 'we encountered a login error!';
}
```

**Comment by malle-pietje** [comment]
Just as a note: I run these basic scripts from the command line to test them.

**Comment by joeladria** [comment]
I still have the same issue with the sample code. With debug enabled I got:

`https://[host]/api/s/default/cmd/devmgr
json={"mac":"f0:9f:fc:c2:64:fc:79","port_idx":7,"cmd":"power-cycle"}
{ "data" : [ ] , "meta" : { "mac" : "f0:9f:fc:c2:64:fc:79" , "msg" : "api.err.UnknownDevice" , "rc" : "error"}}

Notice: Debug: Last error message: api.err.UnknownDevice in /var/www/html/UniFi-API-browser/vendor/art-of-wifi/unifi-api-client/src/Client.php on line 2208
false`

**Comment by malle-pietje** [comment]
Then I'm afraid the MAC address isn't the primary MAC address for the switch you're trying to power cycle a port for. If you don't already have the API Browser tool, please install it and search through the "devices" collection for that MAC address. If correct it will be the value for property ```mac``` of the switch.

**Comment by joeladria** [comment]
Figured it out -- there's no $site_id set, so it was using "default" site which I guess my site was not the default on the controller. That's why it couldn't find the device! Strangely, the site id is NOT the site id that is everywhere in the JSON (In API Browser), but rather the Site ID just above the progress bar (or in the URL of the UniFi controller). 

Do you know what the difference is between those two? hex encoding?

**Comment by malle-pietje** [comment]
Thanks tor the feedback. There is no relationship between the “name” attributes in the site object and the value of the “_id” attribute. The latter is a hash of the numeric index from the database.
