### ISSUE TITLE
POE port control?

### ISSUE THREAD

**Issue by autolog** [Art-of-WiFi/UniFi-API-client#170]
More a question than an issue?

Is it possible to turn the power on or off for a POE port as one can do in the UniFi Controller using Port Management.
I realise there is POE port power cycling but I want to be able to turn POE power off and have it stay off until I turn it on again.

Thanks. :)

**Comment by malle-pietje** [comment]
Please check out this example:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/update_switch_poe-mode.php

and this issue:
https://github.com/Art-of-WiFi/UniFi-API-client/issues/168

**Comment by autolog** [comment]
Thanks for the links. :)
