### ISSUE TITLE
Add Admins?

### ISSUE THREAD

**Issue by smegoff** [Art-of-WiFi/UniFi-API-client#173]
Hello! 

Thanks for the time you put into this project.

I have been looking through the APIs, however I am unable to find anything that will allow you to create an admin for a site?

When you are using a hosted controller, and have many sites, adding a single admin to all those sites is a real PITA.

Cheers

Sean

**Comment by malle-pietje** [comment]
Did you try this out?
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L1756

**Comment by smegoff** [comment]
Hah - you know what, I found that just after I posted. :-)

Typical.

Cheers!
