### ISSUE TITLE
No site-id on dashboard

### ISSUE THREAD

**Issue by andreasloe** [Art-of-WiFi/UniFi-API-client#176]
The commands like block or deblock do not work. I noticed that there is no site-id in dashboard anymore. Might this be the reason?

**Comment by malle-pietje** [comment]
Which dashboard are you referring to? To get the sites’ details you can best first call ```list_sites()```. 

Please also share more details such as controller version and type (UniFi OS or not). These functions still work fine for us on the latest versions.

**Comment by andreasloe** [comment]
Malle-pietje: Thank you very much for sour support and sorry for providing so little information in the first post.

I am using a UniFi OS UCK G2 Plus 2.5.11. In order to block a client I am connecting to Unifi Network 7.2.94. The dashboard I am connecting to is available at https://<ip of cloudkey>/network/default/dashboard

Sicne I am not running php/python yet but rely on the GUI, I do not exactly know where I find the list_sties. I have one network 192.168.2.0/24 and three Wifi-networks. The AP use the newest firmware (6.2.35). Is there anything more I can do?

**Comment by andreasloe** [comment]
Thanks, I tried the API browser before and got a 500 error despite having configured it using the GUI credentials...

**Comment by andreasloe** [comment]
PPS Got it. I needed several commands in case someone runs into the same problem:
`sudo apt-get update && sudo apt-get upgrade -y`
`sudo apt-get install curl`
`sudo apt-get install php-curl`
`sudo service apache2 restart`

**Comment by andreasloe** [comment]
And regarding the first question I now have an answer:
`Error loading sites or no sites available `
Hmm. I am back on square one...

**Comment by malle-pietje** [comment]
What kind of credentials are you using? Does this local user have access to the Network Application for all sites?

**Comment by andreasloe** [comment]
I have two url's I am using:
https://cloudkey.fritz.box/ [this is my local access]
and 
https://unifi.ui.com/dashboard [this is the online access]
and I have used all the credentials that were successful with those sites.

**Comment by malle-pietje** [comment]
Only direct access will work, server-to-server communication isn't supported through unifi.ui.com. Make sure to directly connect to the CloudKey using port 443.

**Comment by andreasloe** [comment]
OK, I checked that - to no avail. I believe that I have write access and I am using the local account. Strange.
<img width="527" alt="Bildschirmfoto 2022-09-27 um 16 34 51" src="https://user-images.githubusercontent.com/10688946/192556005-c91b1570-fad6-425f-b351-f04dab51e883.png">

**Comment by malle-pietje** [comment]
I'm afraid I can't be of any further help but something is definitely wrong with the controller or the credentials.

**Comment by malle-pietje** [comment]
As a last resort you can enable debug mode in the API browser tool and share sanitized logs here.

**Comment by andreasloe** [comment]
Thanks anyway. I believe this has nothing to do with your software because I had the same problem with Perl. I will try this.

**Comment by andreasloe** [comment]
Here is the debug. I cannot see anything suspicious, unfortunately.

`* Connected to cloudkey.fritz.box (2003:cf:572f:e400:7683:XXXX:XXXX:XXXX) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=unifi.local
*  start date: Dec 29 11:50:41 2020 GMT
*  expire date: Apr  3 10:50:41 2023 GMT
*  issuer: CN=unifi.local
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x214b0d0)
> GET / HTTP/2
Host: cloudkey.fritz.box
Accept: */*
Accept-Encoding: deflate, gzip

* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200 
< vary: Origin
< x-dns-prefetch-control: off
< x-frame-options: SAMEORIGIN
< strict-transport-security: max-age=15552000; includeSubDomains
< x-download-options: noopen
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< accept-ranges: bytes
< content-type: text/html; charset=utf-8
< content-length: 595
< x-csrf-token: 1213ccf8-9d1b-43ee-bcd3-XXXXXXXXXX
< x-response-time: 51ms
< set-cookie: TOKEN=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; samesite=none; secure; httponly
< date: Tue, 27 Sep 2022 09:32:59 GMT
`

**Comment by malle-pietje** [comment]
Other than the IPv6 address I don't see anything odd...

**Comment by andreasloe** [comment]
I am just reading this [website](https://myplaceconnect.com/site-id-default-unifi/)

**Comment by malle-pietje** [comment]
This only applies in cases where you have captive portal software connecting to multiple controllers and sites and you have more than 1 default site. Not applicable here.

**Comment by andreasloe** [comment]
Since I have (more or less) the same problem with a completely different software I suspect that Unifi is the culprit. I will now try to open a case in their forum. We can close the case here and I open it if I know more?

**Comment by malle-pietje** [comment]
Ok
