### ISSUE TITLE
Request: DPI app/category information

### ISSUE THREAD

**Issue by inversepolymath** [Art-of-WiFi/UniFi-API-client#18]
When pulling /stat/dpi a list of applications and the relevant data usage is returned. The application and the category they belong to are only identified by a number. Is there a comprehensive list that exists to identify the app/category id to a name?

**Comment by florisvdk** [comment]
https://ubntleaks.com/others/devid.xml Contains the device names
https://ubntleaks.com/others/rule.xml Contains the categories and applications

**Comment by malle-pietje** [comment]
Thanks for that. I assume you extracted this from the controller package?

**Comment by florisvdk** [comment]
Yes, It is in the main jar.
I am looking to script this and make it available automatically for each new controller version.
