### ISSUE TITLE
cURL errors on script run

### ISSUE THREAD

**Issue by FunkyMonk8111** [Art-of-WiFi/UniFi-API-client#186]
Finally got the script the list_user_stats.php script to run, I get the following errors:

PHP Notice:  cURL error: SSL certificate problem: self signed certificate in /root/vendor/art-of-wifi/unifi-api-client/src/Client.php on line 155
PHP Notice:  cURL error: SSL certificate problem: self signed certificate in /root/vendor/art-of-wifi/unifi-api-client/src/Client.php on line 189

Can you give my any insights into this? I wasnt aware of a SSL certificate..

**Comment by malle-pietje** [comment]
Did you read the README file? I am guessing you missed this part:
https://github.com/Art-of-WiFi/UniFi-API-client#important-notes

Specifically:
![image](https://user-images.githubusercontent.com/12016131/222131020-557be4cc-f045-4276-a5b0-d10da4540c3f.png)

**Comment by malle-pietje** [comment]
Feel free to reopen the issue if needed.

**Comment by FunkyMonk8111** [comment]
I think I got it figured out, thanks..

**Comment by FunkyMonk8111** [comment]
Since its not production, I bet there isnt a certificate so I switched it false and it seems to be working, thanks again for pointing that out.
