### ISSUE TITLE
Control PDU Outlets

### ISSUE THREAD

**Issue by samcat116** [Art-of-WiFi/UniFi-API-client#187]
It would be great to be able to control the outlets on the Smart PDU Pro or the Smart Power Strip via the client

**Comment by malle-pietje** [comment]
@samcat116 did you check out this example?
https://github.com/Art-of-WiFi/UniFi-API-client/blob/665fed93e21212146d21b4dfa6b6e8b53efc616f/examples/modify_smartpower_pdu_outlet.php

**Comment by luckman212** [comment]
I have a small Python wrapper to control the outlet of the USP-Plug.

Leaving this here in case it helps anyone

https://github.com/luckman212/unifi-usp-control
