### ISSUE TITLE
Controller url

### ISSUE THREAD

**Issue by zaiterali** [Art-of-WiFi/UniFi-API-client#190]
Hello, 
Im using cloud key gen 2 plus. 
And my login page files hosted on a web server. 

In the config file what should i use for $controllerurl ?

Using both the local controller ip and the public ip not working. 

I think its the forward proccess i miss. 
Anyone can assist me to do this ? 

Thank you.

**Comment by malle-pietje** [comment]
This question is related to pretty basic networking and doesn't belong here I'm afraid. The information you need can all be found in the README file.

**Comment by malle-pietje** [comment]
One small hint:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L56

**Comment by malle-pietje** [comment]
Exactly why I believe this is caused by networking (port forwarding) or firewall rules. Therefore not an issue that belongs here.
