### ISSUE TITLE
Function for changing network on the port of device?

### ISSUE THREAD

**Issue by scgpsro** [Art-of-WiFi/UniFi-API-client#199]
Is it possible to add a direct function to change the VLAN or network for a given device and a given port? So that I don't have to send an instruction to rewrite all ports.

For example:
`set_port_nework(device, port, network_id)`

**Comment by SamuelSchnelly** [comment]
Can someone assign an issue to me?

**Comment by malle-pietje** [comment]
> Can someone assign an issue to me?

Hi, feel free to submit a PR.

**Comment by SamuelSchnelly** [comment]
> > Can someone assign an issue to me?
> 
> Hi, feel free to submit a PR.

hi

Sorry for the late response.

I am a PHP Fullstack developer. I work primarily on projects in the company (which are not public). I primarily work on backends and integration with other systems.

I have experience with the Unifi platform as both a user and a developer. In my diploma thesis, I deal with integration to this infrastructure and automation using the Unifi platform.
