### ISSUE TITLE
Bug in Client.php?

### ISSUE THREAD

**Issue by LuFlo** [Art-of-WiFi/UniFi-API-client#2]
I was looking for a way to add mac filters via an API and I found this project, but I think there is a bug in Client.php
In function` set_wlan_mac_filter` there is following if statement:
`if (in_array($mac_filter_policy, ['allow', 'deny'])) return false;`
Shouldn't it be:
`if (!in_array($mac_filter_policy, ['allow', 'deny'])) return false;`

Otherwise it would return false everytime I give a legit MAC policy.

**Comment by LuFlo** [comment]
And I have a further question: Are MACs which are set previously but not given in "macs" deleted automatically? Or do I have to set the policy to deny in order to "remove" old MAC addresses?

**Comment by malle-pietje** [comment]
Good catch, will fix this asap!

The existing array of macs in the filter will be overwritten by the posted array. See the comments where it says: *replacing existing values*

**Comment by malle-pietje** [comment]
I thought I would fix it straight away. 1.1.22 is OK now.

**Comment by LuFlo** [comment]
OK, thanks a lot!
