### ISSUE TITLE
en/disable port

### ISSUE THREAD

**Issue by vespino** [Art-of-WiFi/UniFi-API-client#201]
I see it's possible to cycle power on a port, but is it possible to en/disable a port?

**Comment by malle-pietje** [comment]
Yes, have a look at this example that is specific to inwalls but the approach is the same. There is a “disabled” switch port profile you need to apply to disable the port and you apply the desired port profile to enable the port:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/update_ac-iw_ports.php

**Comment by vespino** [comment]
Cheers @malle-pietje, I totally overlooked the examples and have now also found this example which seems to do exactly what I was looking for: https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/disable_switch_port.php. I’ll give this a try.
