### ISSUE TITLE
Controller 8.0.2

### ISSUE THREAD

**Issue by aroundmyroom** [Art-of-WiFi/UniFi-API-client#202]
8.0.2 is early access and I do not expect that this is going to work yet, but it seems that the login procedure for this API looks changed

I cannot logon anymore..

**Comment by malle-pietje** [comment]
I haven’t tested this yet. Was this on UniFi OS or was it a software-based controller?

**Comment by aroundmyroom** [comment]
Unifi OS 3.2.5 with controller 8.02 (Cloudkey gen2 plus)
it's not biggy that it is not working and possibly my mistake but it was working before I updated to 8.0.2 ..

**Comment by malle-pietje** [comment]
I've tested the API client here with an ever-newer Network Application version on a UDR, and it works fine. Here's a screenshot from one of our applications:
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/12016131/e5274d24-582f-433c-b184-86c9b6e63867)

**Comment by malle-pietje** [comment]
I am closing this issue now. Please re-open if needed.

**Comment by thib3113** [comment]
Hello @malle-pietje I do some debug on this . 

And it come with unifi OS 3.2.X . In fact this part https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L172-L178 doesn't works with unifi OS > 3.2.X

**Comment by malle-pietje** [comment]
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/12016131/566be6d3-ca0f-4b58-a21e-ddf63a137d76)

**Comment by thib3113** [comment]
@malle-pietje hum ... my bad, re-reading, your library doesn't check the header `x-csrf-token` ... So I don't know why it crash here ... (I got a notification about this issue, and use it to extract the version of the OS/network)

( I'm digging on another libraries , on another language, and it seems that 3.2 stop sending the header `x-csrf-token`, so if the library check on this header to detect unifios/controller, it will stop working on 3.2 ) .

**Comment by malle-pietje** [comment]
@thib3113 Okay, please share the full, sanitised, debug output when logging in and for example fetching the sites. Since I can't reproduce this, I'll have to wait for further data.

**Comment by thib3113** [comment]
@malle-pietje no no ... that's my bad ... I didn't reproduce with this library ... I wrote too fast . 

( as I said, I'm digging this bug, because I got the same with node.js libraries ... and I think the bug here was the same as us ... so "no `x-csrf-token` header" . But, you are not checking it ... so I don't reproduce the same bug )

**Comment by malle-pietje** [comment]
Thanks, understood. Closing this issue.
