### ISSUE TITLE
Suggestio/question Enable/Disable fixed ip on UniFi clients

### ISSUE THREAD

**Issue by Warafux** [Art-of-WiFi/UniFi-API-client#22]
I would like to find a way to fix ips to devices, which can be done through the UI (UniFi->Clients->click on client->Configuration->Network):
![image](https://user-images.githubusercontent.com/23029038/42567303-a1fafb12-8509-11e8-8170-337049f8ad3f.png)
![image](https://user-images.githubusercontent.com/23029038/42567309-a4fce924-8509-11e8-9101-50b69dd64c01.png)
I've been trying to discover the api by myself, in order to make a PUT request into a client and change that field to TRUE.
Listing all clients a "use_fixedip" boolean fields appears:
![image](https://user-images.githubusercontent.com/23029038/42567362-cf806338-8509-11e8-8b61-ba4f39591ac8.png)
Also, a fixed_ip field:
![image](https://user-images.githubusercontent.com/23029038/42567386-e280b294-8509-11e8-960a-73c41cf7aa7c.png)
Is there anyway to actually set the value of that field? 

Thank you.

**Comment by malle-pietje** [comment]
As you may understand, almost everything you can do through the controller UI can be implemented through the API. In this case, the operation uses the `rest/user/` endpoint of the UniFi controller API which is not yet implemented in the API client class.

I will see when I have time to add this in together with some other endpoints which have been requested.

**Comment by Warafux** [comment]
Problem solved, I was messing around with endpoints and didn't find the rest/usr/ endpoint. I was confused with "clients" which wasn't working 
![image](https://user-images.githubusercontent.com/23029038/42568116-4a8d85e0-850c-11e8-8768-d87830413d9e.png)
Thank you again.
