### ISSUE TITLE
Unable to get list of sites from local UCG Ultra

### ISSUE THREAD

**Issue by DibbleJP** [Art-of-WiFi/UniFi-API-client#222]
I have a UCG Ultra running UniFi OS 3.2.12 and network 8.1.113 but when I try to connect it just gives :

Error loading sites or no sites available 

I have set the debug to be true int he config but can't find any debug output anywhere

**Comment by megamacy** [comment]
Why was it closed? Did you find anything? Cant access the UCG Ultra API aswell with the known commands

**Comment by DibbleJP** [comment]
After a reboot of my UCG it just started working ....
