### ISSUE TITLE
Support log in through MFA

### ISSUE THREAD

**Issue by twio142** [Art-of-WiFi/UniFi-API-client#225]
> Starting July 22nd, Multi-Factor Authentication will be mandated for all Ubiquiti Accounts.

[source](https://community.ui.com/questions/Upcoming-Multi-Factor-Authentication-MFA-Requirement-for-All-UI-Accounts-in-July-2024/e0d06d3c-c0ae-4af6-aa67-53c159d486a8)

Any information from Unifi about adding support for MFA over the API?

**Comment by malle-pietje** [comment]
@twio142 that is why this is listed in the README file among the requirements:
“you must use accounts with local access permissions to access the UniFi Controller API through this class”

**Comment by malle-pietje** [comment]
An extensive explanation can be found here on our website:
https://artofwifi.net/blog/important-update-for-all-unifi-api-users-switch-to-local-admin-accounts-before-july-2024
