### ISSUE TITLE
Enable AP auto-update

### ISSUE THREAD

**Issue by SamKr** [Art-of-WiFi/UniFi-API-client#226]
Hi team,

Is it possible to enable 'AP auto-update' through the API and ideally, through your client?

Thanks for sharing this!

**Comment by malle-pietje** [comment]
Yes, the API client supports this. You'll need to use this method:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L1766-L1781

I recommend using the API Browser tool to understand exactly which attributes you need to change in the $payload object/array. My guess is you need to change these attributes:
![image](https://github.com/Art-of-WiFi/UniFi-API-client/assets/12016131/137afde8-2ebc-4dee-9b9a-0081e96573be)

**Comment by SamKr** [comment]
Hi @malle-pietje,

I've been working with the client and the browser and they're both working great, good stuff :)

I just can't seem to get the mgmt part working. Here's what I have so far:

```php
<?php
/**
 * using the composer autoloader
 */
require_once 'vendor/autoload.php';

/**
 * include the config file
 */
require_once 'config.php';

$site_id = $argv[1];

$mgmt_id = $argv[2];

$content = $argv[3];


/**
 * initialize the UniFi API connection class and log in to the controller and pull the requested data
 */
$unifi_connection = new UniFi_API\Client(
    $controlleruser,
    $controllerpassword,
    $controllerurl,
    $site_id,
    $controllerversion
);

$set_debug_mode = $unifi_connection->set_debug($debug);
$loginresults   = $unifi_connection->login();
$result         = $unifi_connection->set_site_mgmt($mgmt_id, $content);

/**
 * output the results in correct json formatting
 */
header('Content-Type: application/json');
echo(json_encode($result, JSON_PRETTY_PRINT));
```

`$site_id` => works, I use that for the list scripts which are all working like a charm. I use the value which also appears in the unifi portal as `/manage/{siteId}/settings/system`

`$mgmt_id`  => I use the _id variable in the `"key": "mgmt"` part from `list_settings()`

`$content` => I have tried both:

```json
[{"auto_upgrade":false,"auto_upgrade_hour":3}]
```

and

```
['auto_upgrade' => false]
```

(note that in this test case I'm trying to get autoupdate to disable)

However autoupgrade stays enabled:

![image](https://github.com/user-attachments/assets/dadbc458-e796-4d46-b9c7-266d0c149647)

**Comment by malle-pietje** [comment]
Next time please share the full code from a minimal working script you are using like I've done in my comment above. That helps eliminate guess work at our end.

In your case it could well be that passing the partial new settings doesn't work. I haven't tested that here, please confirm back whether that was the root-cause of you error or not.

**Comment by SamKr** [comment]
This is working perfectly, so it's probably safe to assume to the partial settings were to blame. 

Thank you so much for the extensive help @malle-pietje, it's really appreciated

**Comment by malle-pietje** [comment]
Good to hear! You're welcome 👍
