### ISSUE TITLE
Out of Memory when fetching large collections (list_devices)

### ISSUE THREAD

**Issue by upcc-jesse** [Art-of-WiFi/UniFi-API-client#245]
One of my sites has about 700 devices, an almost even mix of switches and APs.

When fetching from an API like `list_devices`, the response eventually exceeds the maximum PHP memory limit and errors out. This is at least somewhat mitigated by switching to `list_devices_basic` and/or upping the PHP memory limit. It would be nice to have some pagination, but based on what I know about the controller's built-in API, there is no support for pagination.

I don't think this is a problem that can be solved with the API client itself, then. I guess I'm mainly attempting to put something out there that might show up on a search in case someone hits the same problem I did.

**Comment by malle-pietje** [comment]
At the moment the API doesn’t support paging so increasing the PHP memory limit is currently your only option. As soon as paging comes available we’ll certainly add support for it😉

**Comment by malle-pietje** [comment]
Just wanted to add here that the latest version of the PHP API client has a new function `get_system_log()` where paging has been implemented by the Ubiquiti development team.

More details here:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L3380-L3435

**Comment by malle-pietje** [comment]
Closing issue as it is not directly related to the API client class. Make sure to set your PHP memory limit to appropriate levels for your use case.

**Comment by SheebSuka** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by upcc-jesse** [comment]
The above comment is a phishing link @malle-pietje

**Comment by malle-pietje** [comment]
> The above comment is a phishing link @malle-pietje

Thanks, deleted👍
