### ISSUE TITLE
Which stat is closest to the 'Monthly Data Usage' in the webui?

### ISSUE THREAD

**Issue by csm10495** [Art-of-WiFi/UniFi-API-client#249]
In the web ui for my UCG-Max there is a thing that shows the monthly data usage.  For example:

![image](https://github.com/user-attachments/assets/cf252674-e6c3-450d-8d94-eaa3376ee9ac)

Which api would get me something close to that?  At the moment I'm basically using `report/5minutes.site` then adding up wan-rx_bytes for each entry returned by the API.

At the moment for this month that gets me something like 51.1GiB (1024 bytes per KB) or 54.9GB (1000 bytes per KB). So it doesn't really match what the UI says though I guess is reasonably close. Comcast says 35GB .. but is delayed by a few hours so it may match up tomorrow morning 🤷 .

What is the most accurate API to get this data. I understand the unifi data counting isn't perfect so I'm not asking for byte-by-byte exact numbers, just a reasonably close number of gigs that have gone through the WAN for data cap monitoring purposes.

If what I'm doing makes enough sense, that'd be great too.

As an aside:
Thanks so much for this client. I reversed some key pieces I needed into a random home python script. I tried 3 different python libraries and none were able to easily get this info for me. So after all that I almost gave up, but then decided to run an example of the php code in docker and eventually turned on debug, which pointed me to what I was doing wrong in my python script. Too bad unifi doesn't have an official api with docs, etc. (yet.)

**Comment by malle-pietje** [comment]
In general I recommend using the API Browser tool to browse through the data that is exposed by the main endpoints/methods:
https://github.com/Art-of-WiFi/UniFi-API-browser

Sometimes it does require some testing/validation to be sure your data is as accurate as possible.

**Comment by malle-pietje** [comment]
After a quick look on a UDM PRO I believe this is a good as it gets. You can also check the monthly stats which should be fine if you’re only looking for the monthly numbers although you would need to determine when the stats data aggregation is performed. This should be visible in the server.log file.

**Comment by csm10495** [comment]
Thanks again!

**Comment by csm10495** [comment]
Something interesting of note is that it seems like I can only get the last day or so from /5minutes.site. Even if I request more, only 24 hours seem to come back. Maybe /daily.site would be better at getting more data (to make it to a full month).

**Comment by malle-pietje** [comment]
That makes sense; the data retention configuration determines this. You can see the current values using the 
`list_settings()` method. This gives this output:
```
…
       "data_retention_time_in_hours_for_5minutes_scale": 24,
        "data_retention_time_in_hours_for_monthly_scale": 8760,
        "enable_analytics": false,
        "data_retention_time_in_hours_for_hourly_scale": 168,
        "data_retention_time_in_hours_for_daily_scale": 2160,
…
```
AFAIK you can’t currently change these on UniFi OS consoles.
