### ISSUE TITLE
Capture device id from encrypted url

### ISSUE THREAD

**Issue by alexcalbri** [Art-of-WiFi/UniFi-API-client#250]
I have a code that uses the device id, I was capturing it from the url, but if the url is encrypted it is no longer visible, how can I do it?

**Comment by malle-pietje** [comment]
Perhaps disable the encrypted URL option? We use the PHP Slim framework and that automagically decrypts the URL for us.

**Comment by malle-pietje** [comment]
Not really an issue, rather a discussion topic...

**Comment by alexcalbri** [comment]
thanks
