### ISSUE TITLE
Keep the user connected even when switching sites

### ISSUE THREAD

**Issue by PedroLovatto99** [Art-of-WiFi/UniFi-API-client#252]
Hello, I’m developing a system for customizing forms for networks, where users can select which form they want for a specific network. The controller we’re using is UniFi. My colleague and I based the system on some code and created a version in Python and Django. Everything is working fine, but during testing, we’ve encountered a specific issue.

We connect to the network, access the form, fill in the required information, it validates, and then grants us internet access. So far, so good. However, when testing, we decided to leave that site (or sector) and move to a nearby site that also has access to the same network we were connected to, to see if we remained connected. At first, it stays connected, but after 30 seconds to 1 minute, it disconnects and asks us to reconnect.

How can we keep the user connected? Is there something in the code we can adjust, or is there an option on the controller's website to fix this?

**Comment by malle-pietje** [comment]
Closing issue (it’s not really an issue…) to draw focus to the discussion.
