### ISSUE TITLE
Any way to get the controller version & update controller version?

### ISSUE THREAD

**Issue by OmenLW** [Art-of-WiFi/UniFi-API-client#27]
Is there any way to get the controller version & update controller itself with this API?

**Comment by malle-pietje** [comment]
The method sysinfo() returns an object which contains version details but AFAIK none of the current controller versions support upgrading through the UI (and therefore also the API). I must confess I haven’t spent much time with the latest 5.9.x versions so not sure if that is an upcoming feature.

**Comment by malle-pietje** [comment]
No further feedback received
