### ISSUE TITLE
Template PHP site to register MAC addresses to UniFi Controller

### ISSUE THREAD

**Issue by theotherguy2175** [Art-of-WiFi/UniFi-API-client#29]
Don't know if this would be useful here but, I made a website for our University so that people could register their MAC addresses to the UniFi Controller.  

https://drive.google.com/file/d/1dJtmnQRgQcDxOie3bcrKmzbohzff4gfR/view

Thanks.

**Comment by malle-pietje** [comment]
Thanks for the contribution! Looks like a practical solution that might help others as well.

Feel free to also post a reply to the thread on the UBNT forums:
https://community.ubnt.com/t5/UniFi-Wireless/PHP-class-to-access-the-UniFi-controller-API-updates-and/td-p/1512870

Adding one or more screenshots there will help people to quickly understand the use case before they go through the code.
