### ISSUE TITLE
Suggestion: Would love to see firewall group hooks

### ISSUE THREAD

**Issue by staze** [Art-of-WiFi/UniFi-API-client#3]
Would love to be able to pull the statuscake server list and add that to a firewall group so I could block all other ping responses (as an example).

**Comment by malle-pietje** [comment]
Yeah, firewall groups is one of the things on my to-do list for when I have the time.

**Comment by staze** [comment]
Excellent, thanks!

**Comment by malle-pietje** [comment]
I will be combining that with the ability to get the custom firewall rules and the combined firewall rules from the USG.

**Comment by malle-pietje** [comment]
It took a while but I have now added methods to manage the firewall groups.
