### ISSUE TITLE
How i can use Unifi-Api-client with laravel

### ISSUE THREAD

**Issue by Buendy** [Art-of-WiFi/UniFi-API-client#32]
Hello!

 I'm learning to use Laravel and I would like to implement the API with laravel.
I followed the installation instructions with composer but I have not managed to make it work.
Do you have to do some additional step to the one indicated in the installation steps?

Greetings and thanks!

Sorry for my english.

**Comment by malle-pietje** [comment]
What have you done so far and what are the results/errors? With Laravel it's generally a matter of adding the API client to the `require` section of your `composer.json` file.

This should enable auto-loading so all you need to do in one of your controllers is reference the class like so:
```php
use UniFi_API\Client as UnifiClient;
```

and reference the class like so in one of your methods/functions:
```
...

        $unifi_connection   = new UnifiClient($controlleruser, $controllerpassword, $controllerurl, $siteid, $controllerversion);
...
```

**Comment by Buendy** [comment]
Hi! Sorry for delay.

I installer the API with the composer command: composer require
art-of-wifi/unifi-api-client
After your answer i have seen that i did not do well the reference to the
class.
I still need to learn!
Thanks!

**Comment by malle-pietje** [comment]
You're welcome! Thanks for the feedback.
