### ISSUE TITLE
trigger_error instead of trow

### ISSUE THREAD

**Issue by yTI0r** [Art-of-WiFi/UniFi-API-client#33]
Why for internal errors use **trigger_error()** instead of trow()?
Only in **_constructor()** - **trigger_error()** is on it's place.
Using of **trigger_error** don't allow to use **'try catch'**, instead you must use **set_error_handler()**.
When remote host is not available - it's not a error, it is a 'exception'.

**Comment by malle-pietje** [comment]
I’ve just not taken the time to introduce exceptions. If you wish to add this in, feel free to submit a PR.
