### ISSUE TITLE
Feature Request: Update port forwarding destination

### ISSUE THREAD

**Issue by psyciknz** [Art-of-WiFi/UniFi-API-client#35]
Any chances of working out an api call for updating a port forwarding destination?  For me personally, it would help in fixing a failover from one machine to another thats exposed via port forwarding.

**Comment by malle-pietje** [comment]
I see the use case for this. I’ll need to find some time to look into this and the pending Pull-request for adding/setting firewall rules.

**Comment by psyciknz** [comment]
Cool, was just a situation that came up today, a host went down, and for most of it, I can pull a new container to get my gateway working again, but the more I can automate the easier it is (and to remember the bits), this was one of the pieces in the puzzle.
