### ISSUE TITLE
Getting device status

### ISSUE THREAD

**Issue by host138** [Art-of-WiFi/UniFi-API-client#37]
Hello.
Please tell me, how can i check device is blocked or not by API?
I see only block_sta() and unblock_sta(). 
I looked at the methods list_devices('MAC') and list_guests(), but there also I did not find anything.
In admin area there are difference between blocked and not blocked devices. 
Thank you!

![2019-04-11_121409](https://user-images.githubusercontent.com/35528661/55945421-6f3fbd80-5c53-11e9-9916-feb5b3b1c610.png)

**Comment by malle-pietje** [comment]
To answer such questions yourself, I highly recommend installing our API browser tool, it will allow you to browse the various data collections that are exposed by your UniFi controller(s) in a very simple manner:
https://github.com/Art-of-WiFi/UniFi-API-browser

There you will see that the ```list_users()``` method/function in the API client returns objects for each known device and that a blocked device that has never connected (this was dummy I created) will look like this:
```
...
    {
        "_id": "576cb0ca0cf2d34d219b2b83",
        "site_id": "560f9eda4cf209af30bb244d",
        "mac": "11:22:33:44:55:66",
        "blocked": true,
        "name": "",
        "note": "this is test note",
        "noted": true
    },
...
```
