### ISSUE TITLE
show log usg

### ISSUE THREAD

**Issue by baroninn** [Art-of-WiFi/UniFi-API-client#38]
Hi,
I hope you can help me out.

Im trying to figure out a way to pull the USG logs from firewall... Prefferrably real time...
same command as the SSH command "tail -f /var/log/messages"

I need to be able to import it to a database and make some queries to it, so I can dynamically update my firewall rules... I have a way to dynamically update the firewall rules, but im having a hard time pulling the logs from the USG

Does your api class support this ? err....: pull the /var/log/messages from USG

**Comment by malle-pietje** [comment]
This isn’t something you do through the controller API. Instead, enable remote logging for the site and set up a remote syslog server.

There are many solutions available for near real-time analysis such as Splunk or Graylog:
https://community.ubnt.com/t5/UniFi-Wireless/HowTo-Set-up-a-quick-and-easy-logging-appliance/m-p/2710048#M376624
