### ISSUE TITLE
revoke_voucher not working

### ISSUE THREAD

**Issue by Carlgo11** [Art-of-WiFi/UniFi-API-client#39]
Hello,
I'm trying to handle vouchers using this API and for some reason the `revoke_voucher()` function doesn't seem to work.
I've created a voucher on the Hotspot Manager page. (`65785-57546`)
![hotspot-screenshot](https://user-images.githubusercontent.com/3535780/57805512-5c8e3c00-775d-11e9-9731-a0ad5cdb2961.png)

The vouchers are valid and I'm able to get the voucher's details using  `stat_voucher()`.

When I do:
```PHP
var_dump($unifi_connection->revoke_voucher('6578557546'));
```
it returns true however the voucher is still listed on the Hotspot Manager and I'm able to login to the guest portal using it.

Some debugging I've tried:
* Made sure I was logged in with `$unifi_connection->login()`
* Passed the voucher code directly from `stat_voucher` to `revoke_voucher()`.
* Tried with different voucher codes and one-time use & multi-use codes.
* Checked web server error log (no errors found).

Any ideas?
I'm using PHP 7.2.17, downloaded the project via Composer and my UniFi controller is on version 5.10.23 if that's of any help.
//Carl

**Comment by malle-pietje** [comment]
@Carlgo11 This can easily be explained. The parameter you need to pass with this method id the “_id” value of the voucher, not the voucher code. See the comments here:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L1992

**Comment by Carlgo11** [comment]
Ah okay that worked.
Why did it return true then?

**Comment by malle-pietje** [comment]
Good to hear.

Regarding the results: I’m guessing the API did return “ok” for some reason, if so I don’t know why. You can confirm this by executing get_last_results_raw() after the erroneous call to see the raw results the API returned or by enabling debug mode immediately after constructing your instance of the class.
