### ISSUE TITLE
Port POE enable/disable

### ISSUE THREAD

**Issue by einstein99** [Art-of-WiFi/UniFi-API-client#40]
Can there be a function added to enable/disable/toggle POE setup on a port. My use case is to restart the connected POE-Device and to add a timed on/off for power savings.

**Comment by malle-pietje** [comment]
There is already a function to cycle the POE power on a port:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L2970

To toggle the port state you can use this example to build your own "wrapper" function:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/cd92192cb8e4c0520e6c5039951fc372e89c604f/examples/update_ac-iw_ports.php

So there is no need to create another specific function for this in the API client class.

**Comment by einstein99** [comment]
Thanks for the hint. I just had seen the power toggle, what did not match all my needs. The port-conf does what's left. :)

**Comment by einstein99** [comment]
Actually i am not sure, if any of those functions works for me. the powercycle only works for the reset, but it can not be used to keep the device off for some time. Buy using the update_ac-iw_ports, it updates _all_ ports, not only the configured ones. By that, everytime i use the UI for switch configuration, it just lasts until i call the script again. I did not find a "get_device_settings_base" what i could use for scripting. Is there any chance, to get the running config or set only specific ports?

The lib is quite fast, so the effort to script it and set every port not specifically configured to what it was before is probably not that big a deal from performance point of view.

**Comment by malle-pietje** [comment]
You’re welcome. When I can find the time I’ll add an example wrapper for this to the examples that is more aimed at generic switches.

**Comment by malle-pietje** [comment]
Can you share the code you have tried so far?

**Comment by einstein99** [comment]
I am currently using the example in update_ac-iw_ports.php; I did not modify it a lot as i did not thoroughly read the documentation. I expected, it will merely fiddle with the ports listed in the array, but it seems to do all of them as "Default" and the not listed ones as whatever is in the array. I will have a look, if i can use either list_devices or list_portconf function to achieve a "per port" update and leave anything else untouched.

**Comment by einstein99** [comment]
I extended the update_ac-iw_ports example for a function to keep existing config's and add new one's if no config was there already. For now it works with poe and port-status. I did so, as even if the port was disabled, the poe-device was still online. I tried to put comments there, but it looks not so nice (and straightforward) as the existing examples. 
[config.php.txt](https://github.com/Art-of-WiFi/UniFi-API-client/files/3237720/config.php.txt)
[disableports.php.txt](https://github.com/Art-of-WiFi/UniFi-API-client/files/3237721/disableports.php.txt)

I hope, you can understand the mess and use it to add it to the examples.

Thanks for the lib and support. :)

**Comment by malle-pietje** [comment]
Thanks for the feedback and contribution! And glad you like the library:wink:

I'll review and add this to the examples in the repo as soon as I have the time.

**Comment by Kaltt** [comment]
The Example looks interesting, but it would help if there would be some additional comments about how configure it. I was not able to make it running. I am looking forward to get some more hints how to configure it. 
Thank you

**Comment by malle-pietje** [comment]
@Kaltt Can you share the code you used and explain what the exact error is that you encountered?

**Comment by Kaltt** [comment]
I used the example code posted in this thread and I get the following output: falsefalse

I defined in the example file disableports.php the following
$site_id = 'default'; --> I assume that default is okay, as I access the controller with the following link: https://192.168.1.3:8443/manage/site/default/dashboard
$device_mac = '18:18:18:18:18:18'; --> I assume that this is the mac address of the switch where I would like to disable the poe
$lanports = (5); --> I assume that this is just the number of the port where I would like to disabel the poe of my unifi UniFi Switch 8 POE-60W

I saw that in the config example file the following was included as well. What are these for? 
define('Disabled', '58f114ad79e0043e5cd0e5aa');
define('Guest', '5b142e3019eb3906cadb1542');
define('All', '58f114ad79e0043e5cd0e5a9');

**Comment by malle-pietje** [comment]
Maybe @einstein99 can chip here? From a first glance, I believe the declaration of $lanports should be done like so:
```php
$lanports = [5];
```
At least, I assume we need to have an array here.

**Comment by Kaltt** [comment]
@malle-pietje : it is amazing how fast you reply, thank you a lot!!
I tried it out, I got the following: 9,LHfalsefalse

**Comment by malle-pietje** [comment]
The declaration of the constants (define...) is for easier reference to the port profile ids throughout the code. These ids will be different for each site so you should check the port profiles you have available first.
IIRC you can use this method for that:
```
list_portconf();
```

**Comment by Kaltt** [comment]
I assume I can use it like that: 
$list_portconf    = list_portconf();
echo json_encode($list_portconf, JSON_PRETTY_PRINT);

**Comment by malle-pietje** [comment]
Yes, or use the API browser tool:
https://github.com/Art-of-WiFi/UniFi-API-browser

**Comment by Kaltt** [comment]
Okay I will try it out, but with the above I got the same feedback "9,LHfalse", so no additional output.

**Comment by malle-pietje** [comment]
Hmm, I guess we need to wait for @einstein99 :wink:

**Comment by Kaltt** [comment]
I realized that I had to enter https:// in the config file, now I got the following: 9,LH{ "meta": { "rc": "error", "msg": "api.err.Invalid" }, "data": [] }

**Comment by Kaltt** [comment]
I found the issue, there was a statment too much in "$new_ports_config". 
If I manually overwrite the variable with a correct statment, I do not get an error anymore, I get a "true" statement from "$update_device = $unifi_connection->set_device_settings_base(...)"
But the port poe is not switched off. 
The argument that I send in as part of the "$new_ports_config" looks like the following for one port of the UniFi Switch 8 POE-60W: 
{ "port_idx": 5, "portconf_id": "xxxxxxxxxxxx", "poe_mode": "off", "name": "UniFi AP Wohnzimmer" }
Any idea?

**Comment by einstein99** [comment]
Hi, sorry for late reply. I used the two examples in the posted files to keep any already done configuration, but modify the poe_mode setting. For explanation:
The site_id as 'default' is probably fine. All environments maintained by me work with only /default/, if accessed via Web UI, so i cannot say, when this is needed to change.
The defines for "Guest, Disabled and All" are profiles for Ports configured on the controller. I sometimes use the Web-UI to modify stuff and then assign those profiles to ports. The ID's had been extracted from Web-UI while configuring the profiles. Within the scripts i can use those profile names or (more ugly, but more direct) the id's to assing the profiles to ports. I integrated the api into smart home, to toggle a port between "Guest" and "All"
To actually toggle the ports, i list the ports in $lanports. The example is in disableports.php. That script is still active and working. 

Can you pls. post the example/files you have, as i am not sure what you already solved and what is the expected output.

Thanks.

**Comment by Kaltt** [comment]
Thank you @malle-pietje  & @einstein99 ! With your help I was able to change the example to my needs. 
I updated the example that you can provide an input value "off" or "auto", in order to specify if you would like to turn off or on the poe_mode of the predefined ports. 
In the example attached I included some comments as well, I hope this will help some other people later as well. 
[update_switch_poe-mode.php.txt](https://github.com/Art-of-WiFi/UniFi-API-client/files/3522552/update_switch_poe-mode.php.txt)
