### ISSUE TITLE
Login Does not Work with API

### ISSUE THREAD

**Issue by Jack-Piotrowski-MAT-Holdings** [Art-of-WiFi/UniFi-API-client#41]
Hi,

I have cloned the UniFi-API-client repository, loaded its libraries with composer and filled out the config appropriately with the correct username, password, https://*.*.*.*:8443, and my controller version.

I then created a new file 'login.php':
___________________________________________________________________________________________________
require_once("vendor\autoload.php");
require_once('config.php');
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login();
___________________________________________________________________________________________________

I do not get any errors on loading:
require_once("vendor\autoload.php");
require_once('config.php');

Contents of config.php: 
___________________________________________________________________________________________________
$controlleruser     = 'admin'; // the user name for access to the UniFi Controller
$controllerpassword = '*********'; // the password for access to the UniFi Controller
$controllerurl      = 'https://*.*.*.*:8443'; // full url to the UniFi Controller, eg. 'https://22.22.11.11:8443'
$controllerversion  = '5.10.23'; // the version of the Controller software, eg. '4.6.6' (must be at least 4.0.0)
$debug = false;
___________________________________________________________________________________________________

The login function simply returns "false", so it is not getting the $_SESSION['unificookie'] value.

I checked all of the settings on my controller's UI, and I did not find anything I needed to enable to allow calls like this.

Do you know of anything in the Controller UI that might fix this problem? 

Maybe my client.php's config values?

client.php config values:
___________________________________________________________________________________________________
    protected $baseurl            = 'https://127.0.0.1:8443';
    protected $user               = 'admin';
    protected $password           = '************';
    protected $site               = 'https://*.*.*.*:8443';
    protected $version            = '5.10.23';
___________________________________________________________________________________________________

Should the $baseurl be something other than my local host? 

I appreciate any and all help!

Thank you,

Jack

**Comment by malle-pietje** [comment]
First of all, you should never need to change the contents of the `Client.php` file. The protected properties there have a purpose.

Secondly I believe you’re using an incorrect value for site_id, the fourth parameter for the constructor. Please read this section of the README:
https://github.com/Art-of-WiFi/UniFi-API-client#important-notes

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
Okay, I just undid all changes I made to the Client.php file. 

So now the constructor looks like this:
![image](https://user-images.githubusercontent.com/42820264/59386392-2b893300-8d2c-11e9-97b2-3415807a8dbc.png)

I read the Important Notes section, went to my Controller's UI and found this in the url:
https://<UniFi IP>:8443/manage/site/default/dashboard

So 'default' is my $site_id

So I changed the $site value (4th variable in Client.php's constructor) to 'default' 

When I saved everything and refreshed the page that my login script is running it still returned 'false.'

Is there anything else that might be the culprit?

Thank you for your help,

Jack

**Comment by malle-pietje** [comment]
Can you enable debug mode (pass true without quotes) and see what the output is?

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
login failed

-----------LOGIN-------------
Array
(
    [url] => https://10.5.135.254:8443/api/login
    [content_type] => application/json;charset=UTF-8
    [http_code] => 200
    [header_size] => 444
    [request_size] => 223
    [filetime] => -1
    [ssl_verify_result] => 18
    [redirect_count] => 0
    [total_time] => 1.248
    [namelookup_time] => 1.0E-6
    [connect_time] => 0.062
    [pretransfer_time] => 0.593
    [size_upload] => 46
    [size_download] => 30
    [speed_download] => 24
    [speed_upload] => 36
    [download_content_length] => 30
    [upload_content_length] => 46
    [starttransfer_time] => 1.248
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 10.5.135.254
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => 10.1.101.132
    [local_port] => 52214
)

----------RESPONSE-----------
HTTP/1.1 200 
vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
Set-Cookie: unifises=KEZyGHcNvBodd0qEg1z284vO3CBbojK0; Path=/; Secure; HttpOnly
Set-Cookie: csrf_token=y7NoFBMBd4yynJ57TCeWoZvxJb0KFwE5; Path=/; Secure
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Content-Length: 30
Date: Wed, 12 Jun 2019 21:22:07 GMT

{"meta":{"rc":"ok"},"data":[]}
-----------------------------

---------cURL INFO-----------
Array
(
    [url] => https://10.5.135.254:8443/api/s//cmd/stamgr
    [content_type] => 
    [http_code] => 400
    [header_size] => 101
    [request_size] => 338
    [filetime] => -1
    [ssl_verify_result] => 18
    [redirect_count] => 0
    [total_time] => 0.608
    [namelookup_time] => 1.0E-6
    [connect_time] => 0.031
    [pretransfer_time] => 0.561
    [size_upload] => 92
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 151
    [download_content_length] => -1
    [upload_content_length] => 92
    [starttransfer_time] => 0.608
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 10.5.135.254
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => 10.1.101.132
    [local_port] => 52215
    [request_header] => POST /api/s//cmd/stamgr HTTP/1.1
Host: 10.5.135.254:8443
Accept: */*
Cookie: unifises=KEZyGHcNvBodd0qEg1z284vO3CBbojK0;csrf_token=y7NoFBMBd4yynJ57TCeWoZvxJb0KFwE5
Content-Type: application/json
Content-Length: 92


)

-------URL & PAYLOAD---------
https://10.5.135.254:8443/api/s//cmd/stamgr
{"cmd":"authorize-guest","mac":"","minutes":2000}
----------RESPONSE-----------

-----------------------------

false

---------cURL INFO-----------
Array
(
    [url] => https://10.5.135.254:8443/logout
    [content_type] => 
    [http_code] => 302
    [header_size] => 336
    [request_size] => 157
    [filetime] => -1
    [ssl_verify_result] => 18
    [redirect_count] => 0
    [total_time] => 0.64
    [namelookup_time] => 1.0E-6
    [connect_time] => 0.047
    [pretransfer_time] => 0.577
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => 0
    [upload_content_length] => -1
    [starttransfer_time] => 0.64
    [redirect_time] => 0
    [redirect_url] => https://10.5.135.254:8443/manage
    [primary_ip] => 10.5.135.254
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => 10.1.101.132
    [local_port] => 52218
    [request_header] => GET /logout HTTP/1.1
Host: 10.5.135.254:8443
Accept: */*
Cookie: unifises=KEZyGHcNvBodd0qEg1z284vO3CBbojK0;csrf_token=y7NoFBMBd4yynJ57TCeWoZvxJb0KFwE5


)

-------URL & PAYLOAD---------
https://10.5.135.254:8443/logout
empty payload
----------RESPONSE-----------

-----------------------------

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
That debug response is actually for this code:
(very slightly different than the code I posted before--taken from auth_guest_basic.php)

require_once("vendor\autoload.php");
require_once('config.php');
$mac = '<enter MAC address of guest device to auth>';
$duration = 2000;
$site_id = 'default';
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login();
$auth_result = $unifi_connection->authorize_guest($mac, $duration);
echo json_encode($auth_result, JSON_PRETTY_PRINT);

**Comment by malle-pietje** [comment]
Hmmm, I’m not seeing the string “default” in the URLs. Are you 100% sure you are passing the value in the correct way?

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
Well the 'default' string should be inserted into the URL inside of the login() function, right?

And I include the config and create a new instance of the Client class, so it should be getting the $site_id value from Client.php, which has it set to 'default'.

**Comment by malle-pietje** [comment]
Also make sure you pass a valid MAC address to this function.

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
I added a valid MAC address to the function. Still same results.

**Comment by malle-pietje** [comment]
Thats not how PHP OOP programming works. The constructor creates a new instance of the Class which has several specific properties such as the site id.

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
Oh, wait! I hard-coded 'default' as the site_id:
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, 'default', $controllerversion);

And it returned true. 

So what do I have to change to make it so $site_id in the below line of code actually refers to the $site value inside of Client.php?:
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);

Something like this?

$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $unifi_connection->site, $controllerversion);

**Comment by Jack-Piotrowski-MAT-Holdings** [comment]
I'm sorry, nevermind. I figured it out.

Thank you so very much for taking the time to help me.

I hope you have a wonderful morning/afternoon/night wherever you are!

Best regards,

Jack

**Comment by malle-pietje** [comment]
No problem, you're welcome. You too, here it's almost midnight (CET timezone).

By the way, feel free to share the resolution here for other readers.
