### ISSUE TITLE
Retrieve Speed Test Results

### ISSUE THREAD

**Issue by marcolino7** [Art-of-WiFi/UniFi-API-client#42]
UNIFI Controller has capability to chedule a speedtest for checking connectity of the provider.
Is there a way to retrieve the result of last speedtest via this API?

Thanks

**Comment by malle-pietje** [comment]
Did you go through the README or the actual Class file itself? The ```stat_speedtest_results()``` functions allows you to do this.

**Comment by marcolino7** [comment]
Hi, running this code:

`$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login();
$user_array        = $unifi_connection->stat_speedtest_results();`

I am able to retrieve lastest speedtests, but the [time] in epoch format, have  three zero at the end:
`{"_id":"5d05fd39d6018000125aa915","latency":11,"xput_download":160.05137634277,"xput_upload":20.225742340088,"o":"speedtest","oid":"5b55aa08e21b8400126e97c4","time":1560673593000}`

This cause the epoch conversion fail.
Any help on this?

Thanks

**Comment by malle-pietje** [comment]
Then the controller is simply returning milliseconds. Just divide by 1000 and round the results... use Carbon to format the timestamp, it has a lot of interesting features.

**Comment by malle-pietje** [comment]
Carbon’s createFromTimestampMs() function will do the conversion for you.

**Comment by marcolino7** [comment]
I don't know carbon and I am not a PHP expert. Do you have a link with some example?

Thanks

**Comment by malle-pietje** [comment]
Although not something that is appropriate here, here's a quick example:
```
$timestamp_ms = $speedtest_result['time'];
$dt = Carbon::createFromTimestampMs($timestamp_ms);
echo $dt->format('l jS \\of F Y h:i:s A'); // will be formatted like "Thursday 25th of December 1975 02:15:16 PM"
```
More details on Carbon can be found here:
https://carbon.nesbot.com/

**Comment by marcolino7** [comment]
All done.
Many Thanks

**Comment by malle-pietje** [comment]
You're welcome! Good luck.
