### ISSUE TITLE
Last seen date/time not updating

### ISSUE THREAD

**Issue by ale1981** [Art-of-WiFi/UniFi-API-client#46]
The last seen date & time seems to be different to the controller GUI, it doesn't seem to update?

using $unifi->stat_allusers(24);

Unifi 5.10.26-11685-1

**Comment by malle-pietje** [comment]
@ale1981 That is because the UniFi controller view consolidates the results from `stat_allusers()` and of `list_clients()`. The latter contains more current information than the former.

There's nothing stopping you from doing the same.

**Comment by ale1981** [comment]
Thanks for the quick response, You are correct, using list_clients() gives a more accurate last seen date & time. Strange that the stat_allusers() isn't using the same last seen timestamp!

**Comment by malle-pietje** [comment]
Probably the known clients collection is being created/updated at specific intervals
