### ISSUE TITLE
How do I create a Custom code for the create_voucher function, let's say an alphanumeric code instead of a string of numbers

### ISSUE THREAD

**Issue by Maxwellkurt0407** [Art-of-WiFi/UniFi-API-client#47]
this is the result of the script that I ran:

[ { "_id": "5d81c805609b0e273c25796e", "site_id": "5d81a22c609b0e1278b62e9a", "create_time": 1568786437, "code": "6386473243", "for_hotspot": false, "admin_name": "admin", "quota": 0, "duration": 2000, "used": 0, "qos_overwrite": false, "note": "sadofnowe:}{:", "status": "VALID_MULTI", "status_expires": 0 } ]

How do I make a custom value/string for "code"

eg. "code":"asodoiw124"
instead of "code": "6386473243"

**Comment by malle-pietje** [comment]
I’m afraid this isn’t possible the API; the controller generates the randomized voucher codes after it receives the request to create X vouchers.

You could try to change the voucher codes through direct interaction with the MongoDB database but I’m not sure if such a change will work with any input validation there may be.

**Comment by Maxwellkurt0407** [comment]
> 
> 
> I’m afraid this isn’t possible through the API; the controller generates the randomized voucher codes after it receives the request to create X vouchers.
> 
> You could try to change the voucher codes through direct interaction with the MongoDB database but I’m not sure if such a change will work with any input validation there may be.

I have tried to update the voucher code directly in the mongodb database using robo 3t. If I change the numbers with numbers, it can be validated at the portal. However, when I change the voucher code and turn it into alphanumeric, it doesn't work. Do you have an idea where the authentication occurs?
I am using unifi controller 5.11.46

**Comment by malle-pietje** [comment]
@Maxwellkurt0407 As I expected: the validation is performed in Java code within the controller. This cannot be changed I’m afraid.

If this is important to you your only option is to build your own external captive portal with your own custom voucher implementation.

**Comment by Maxwellkurt0407** [comment]
@malle-pietje Thank you for the clarification on the above mentioned query. In the API, is the function unauthorize_guest() the same as disconnecting it from the guest list?
