### ISSUE TITLE
changing guest portal password

### ISSUE THREAD

**Issue by vespino** [Art-of-WiFi/UniFi-API-client#48]
I was wondering if it is possible to change the password for the guest portal like it is possible to change the WLAN password using the API.

**Comment by malle-pietje** [comment]
Yes, this can be found when calling list_settings() where "key" = "guest_access". Then modify the settings and push them back using this function:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L1577

**Comment by vespino** [comment]
Thanks, I’ll give that a try.

**Comment by malle-pietje** [comment]
OK, feel free to re-open this issue if any questions pop up.
