### ISSUE TITLE
Extend Guest Connection with Time Parameter

### ISSUE THREAD

**Issue by Maxwellkurt0407** [Art-of-WiFi/UniFi-API-client#49]
Good Day, here's the situation:
For instance, I have a guest that is already connected to an AP, and I want to extend his/her connection. How do I do that?

I've seen this function:
   ```
 public function extend_guest_validity($guest_id)
    {
        if (!$this->is_loggedin) {
            return false;
        }

        $payload  = ['_id' => $guest_id, 'cmd' => 'extend'];
        $response = $this->exec_curl('/api/s/' . $this->site . '/cmd/hotspot', $payload);

        return $this->process_response_boolean($response);
    }
```

How Will I use it to extend the connection with a specific time?

**Comment by malle-pietje** [comment]
This function is also used by the controller UI but the extension duration is sometime unpredictable, also through the API. Best approach is to simply issue an auth request for the required extension period.
