### ISSUE TITLE
sitemgr not work anymore

### ISSUE THREAD

**Issue by sergiomfsilva** [Art-of-WiFi/UniFi-API-client#5]
Hi, 

I am working on unify version 5.5.24 and every time that I try to use methods that use sitemgr url this fails.

I am try to create and delete some test sites and the error is always the same, api.err.NoSiteContext but if i use list_settings on a site the SiteContext works.

But in all the cases curl debug give [http_code] => 401 - UNAUTHORIZED

I tried using the code in localhost and others ways but did not find the issue that I am doing or not.

sitemgr url still its working in 5.5.24?

Best Regards

**Comment by malle-pietje** [comment]
Let me check this. Could very well be that the new version uses true REST routes but will ll need to confirm. I’ll be back shortly with some feedback.

**Comment by malle-pietje** [comment]
I looked into this and I have no issues whatsoever using the ```delete_site()``` and ```delete_site()``` functions/methods. You need to understand that the client needs to be "logged in" to another site before being able to create a site or delete one.

Here's the major part of the code I used to test this:
```php
<?php
require_once('../UniFi-API-client/src/Client.php');

/**
 * include the config file (place your credentials etc. there if not already present)
 * see the config.template.php file for an example
 */
require_once('config.php');

/**
 * the site to use
 */
$site_id = '<short site name of a site the credentials used have access to>';

/**
 * description of the new site
 */
$description = 'new site';

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$loginresults     = $unifi_connection->login();
$results          = $unifi_connection->create_site($description);

/**
 * provide feedback in json format
 */
echo json_encode($results, JSON_PRETTY_PRINT);
```

**Comment by malle-pietje** [comment]
And for site deletion:
```php
<?php
require_once('../UniFi-API-client/src/Client.php');

/**
 * include the config file (place your credentials etc. there if not already present)
 * see the config.template.php file for an example
 */
require_once('config.php');

/**
 * the site to use
 */
$site_id = 'mdfwaanp';

/**
 * _id value of the the site to delete
 */
$site_to_delete = '5a05734c0cf23d58735bf9e3';

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$loginresults     = $unifi_connection->login();
$results          = $unifi_connection->delete_site($site_to_delete);

/**
 * provide feedback in json format
 */
echo json_encode($results, JSON_PRETTY_PRINT);
```

Both these calls return "true" as expected.

**Comment by malle-pietje** [comment]
FYI, these two examples will be added to the repo with the next commit.

**Comment by sergiomfsilva** [comment]
Hi, thanks. 

Yes, all is ok like you said. Please close this issue. 

I have two issues, one related with permissions and other related with a old unifi controller with a lot of updates and a mix of auto generate site name and user defined site name, and this confuse me.

Best regards

**Comment by malle-pietje** [comment]
Glad to hear this works for you!
