### ISSUE TITLE
list_sites() only returns the first 2997 sites

### ISSUE THREAD

**Issue by scottchiefbaker** [Art-of-WiFi/UniFi-API-client#51]
I have what I think may be a unique problem... We're an ISP that provides Unifi WiFi to our members. Each member has their own site in our controller, so we have a rather **large** controller. Our controller has just about 3000 sites on it.

`list_sites()` only returns the first 2997 sites no matter how many sites are actually on the controller. I've tested it by adding 50 sites at a time, as soon as the total is above 2997 it stops returning all the sites. My guess is that the Unifi controller limits how many sites it returns via that API call? Do you know any way to work around this limitation?

We're currently running 5.12.35 of the Unifi controller software.

**Comment by malle-pietje** [comment]
Hmmm, interesting. I've used the PHP API client class on projects with large controllers (up to 1800 sites) but not of this size. How can you verify the number of sites; doe the UniFi controller UI display all sites correctly?
One other thing to test is enabling debug mode in the PHP API client instance like so immediately after instantiation:
```php
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion, true);
$set_debug_mode   = $unifi_connection->set_debug(true);
```
Can you share the exact PHP and cURL version you are using? Maybe there's a limitation there?

**Comment by malle-pietje** [comment]
If needed we can do a screen sharing session over Skype or TeamViewer to perform some diagnostics. If so, please reach out via email to erik AT artofwifi DOT net

**Comment by scottchiefbaker** [comment]
We're running PHP 7.2.16 and Curl 7.55.1 (built in to PHP).

I can verify the number of sites on the controller by counting the sites when I backup/dump the Unifi DB. We start having issues with `list_sites()` as soon as we hit ~3000 sites.

I've enabled debug mode in my code and this is the response for the `list_sites()` command:

```
---------cURL INFO-----------
Array
(
    [url] => https://x.x.x.x:8443/api/self/sites
    [content_type] => application/json;charset=UTF-8
    [http_code] => 200
    [header_size] => 378
    [request_size] => 166
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.247678
    [namelookup_time] => 5.0E-5
    [connect_time] => 0.000941
    [pretransfer_time] => 0.062406
    [size_upload] => 0
    [size_download] => 306415
    [speed_download] => 1237150
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0.186495
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => x.x.x.x
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => x.x.x.x
    [local_port] => 39284
    [request_header] => GET /api/self/sites HTTP/1.1
Host: x.x.x.x:8443
Accept: */*
Cookie: unifises=hLUegM4ar07z8SB7cLmEDkiWTd1GQuav;csrf_token=NjSSwDp1jn2YryFn9IRMRE9ruh1hXLz6


)
```

I don't see much there.

**Comment by scottchiefbaker** [comment]
It's worth noting that everything else appears to work fine on the controller and the API, it's just `list_sites()` that appears to be limited.

**Comment by malle-pietje** [comment]
Hmm, an empty response isn’t good... Let me check and get back to you.

**Comment by scottchiefbaker** [comment]
Where do you see an empty reply? 

    [size_download] => 306415

I didn't include the actual payload because it's just 2997 sites from my controller. Like I said, I can connect and retrieve data, it's just truncated at 3000.

**Comment by malle-pietje** [comment]
Ok, I misunderstood your post. Do you see all sites through the UniFi user interface?

**Comment by malle-pietje** [comment]
Any possibility to follow up on this or shall we close this issue?

**Comment by scottchiefbaker** [comment]
Oh sorry I forgot to follow up... We're testing a couple different versions of the Unifi controller. As it stands right now all the versions of the controller we've tested seem to max out at ~3000 sites in their UI as well.

This is most likely a Unifi bug/feature and nothing to do with the API.

**Comment by malle-pietje** [comment]
No problems. I may try to create a bit of code for you to test, will keep you posted.

**Comment by malle-pietje** [comment]
Hmmm, my idea didn't fly I'm afraid. For now, we'll have to accept the limit of just under 3000 sites per controller...
