### ISSUE TITLE
block_list / unblock_list don't exit

### ISSUE THREAD

**Issue by johnluber** [Art-of-WiFi/UniFi-API-client#53]
I've got a new UDM Pro and was looking for a way to enable/disable my kid's gaming systems so they don't overuse them.  I found your scripts and they will definitely do the job if I can sole one thing.

Currently, they do block and unblock as expected, but neither script ends unless you hit ctrl-c.

I'm not a strong programmer but I've tried adding an exit after the for loop but that doesn't seem to work.  

Any ideas?

**Comment by malle-pietje** [comment]
Can you please share your code (without the credentials) so we can have look?

**Comment by johnluber** [comment]
I just used the code samples that you have on GitHub for block_list and unblock_list and am passing 3 comma separated Mac addresses as input.

I did have to hard code the values for $unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion); because I could not get them to load from the config file.

Otherwise, it's exactly the example code.

I can send some debug if you'd like.  It appears as though after it blocks/unblocks the 3 Macs it then continues to read from the controller.  It looks like a continuous stream of data coming back.

**Comment by johnluber** [comment]
So, here's an 8 second debug run of unblock_list(I'm using timeout to kill it).  From this 'file' contains the actual output of the MAC addresses being unblocked and 'debug' contains the extraneous output that happens after the last MAC is unblocked up until the script is killed by timeout.

Note: some private info was deleted from file.txt
[file.txt](https://github.com/Art-of-WiFi/UniFi-API-client/files/4237789/file.txt)
[debug.txt](https://github.com/Art-of-WiFi/UniFi-API-client/files/4237790/debug.txt)

BTW - thank you so much for putting your time into this.  Since UBNT has killed config.gateway.json you've provided me an alternative to my kids play video games non-stop.  :)

**Comment by malle-pietje** [comment]
Can try the code with the logout call commented out? It looks as if the route is incorrect.

**Comment by johnluber** [comment]
ok, I tried that and go the same result.  So, then I put a simple print statement in place of the logout and that's where the code sits.  It seems like it never exits the foreach loop even though it processes each of the 3 MAC addresses I am passing it.

**Comment by malle-pietje** [comment]
Hmm, can you then share the exact code you are using so I can check it? By the way, I will be releasing a version of the package that fixes the logout URL later today.

**Comment by johnluber** [comment]
Yes, here it is:

<?php
/**
 * PHP API usage example
 *
 * contributed by: @malcolmcif, based on another Art of WiFi example
 * description: basic PHP script to block a list of mac addresses passed in via command line,
 *              output is to console in non json format
 *
 * usage:
 *  php block_list.php <list of comma seperated mac addresses>
 *
 * example:
 *  php block_list.php 09:09:09:09:09:09,10:10:10:10:10:10
 *
 */

/**
 * using the composer autoloader
 */
require_once('vendor/autoload.php');

/**
 * include the config file (place your credentials etc. there if not already present)
 * see the config.template.php file for an example
 */
require_once('config.php');
$debug = false;

/**
 * the MAC address(es) of the device(s) to block
 */
$macs_to_block = explode(',', $argv[1]);

/**
 * The site to authorize the device with
 */
$site_id = 'default';
if ($site_id == "MUST_DEFINE_THIS") {
    print 'ERROR: set the site id in your script';
    return;
}

/**
 * initialize the UniFi API connection class and log in to the controller
 */
$unifi_connection = new UniFi_API\Client('XXXXXX', 'XXXXX', 'https://W.X.Y.Z', 'default', '5.12.63');
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login(); // always true regardless of site id

foreach ($macs_to_block as &$mac) {
    // block_result is always true even if mac address does not exist :(
    $block_result = $unifi_connection->block_sta($mac);

    /**
     * NOTE:
     * during testing I had some strange behavior where clients were not reconnecting to the network correctly,
     * they appeared unblocked and received a valid IP address but could not actually get any data.
     * the clients did not come to life until I disabled the SSID and then re enabled it.
     * I guessed maybe these commands were occurring too quickly for the controller so I have slowed them down;
     * since introducing the sleep I have not seen the above behavior so it might be fixed
     */
    sleep(1);

    $getid_result = $unifi_connection->stat_client($mac);

    if (property_exists($getid_result[0], "oui")) {
        // this field(manufacturer) seems to exist on valid mac addresses
        if (property_exists($getid_result[0], "name")) {
            // this is the alias field if it has been defined
            $name = $getid_result[0]->name;
        } else {
            $name = $getid_result[0]->hostname;
        }
        print 'blocked ' . $name . PHP_EOL;
    } else {
        print 'ERROR: could not block ' . $mac . PHP_EOL;
        print '       check mac address is valid and part of your network' . PHP_EOL;
    }
}
$loginresults     = $unifi_connection->logout(); // always true regardless of site id
?>

**Comment by johnluber** [comment]
Yes, here you go:  

[block_list.php.txt](https://github.com/Art-of-WiFi/UniFi-API-client/files/4239563/block_list.php.txt)

**Comment by malle-pietje** [comment]
Can please use markup to make it more readable?
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by johnluber** [comment]
I took down the copy & paste and re-added it as a file upload so the formatting would be better.

**Comment by malle-pietje** [comment]
OK, thanks, I've tested part of your 

```php
<?php
/**
 * PHP API usage example
 *
 * contributed by: Art of WiFi
 * description: example basic PHP script to pull current alarms from the UniFi controller and output in json format
 */
/**
 * using the composer autoloader
 */
require_once('vendor/autoload.php');

/**
 * include the config file (place your credentials etc. there if not already present)
 * see the config.template.php file for an example
 */
require_once('config.php');

/**
 * the site to use
 */
$site_id = 'default';

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */
$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion, false, true);
$set_debug_mode   = $unifi_connection->set_debug(true);
$loginresults     = $unifi_connection->login();

/**
 * the MAC address(es) of the device(s) to block
 */
$macs_to_block = explode(',', $argv[1]);

foreach ($macs_to_block as &$mac) {
    // block_result is always true even if mac address does not exist :(
    $block_result = $unifi_connection->block_sta($mac);

    /**
     * NOTE:
     * during testing I had some strange behavior where clients were not reconnecting to the network correctly,
     * they appeared unblocked and received a valid IP address but could not actually get any data.
     * the clients did not come to life until I disabled the SSID and then re enabled it.
     * I guessed maybe these commands were occurring too quickly for the controller so I have slowed them down;
     * since introducing the sleep I have not seen the above behavior so it might be fixed
     */
    sleep(1);

    $getid_result = $unifi_connection->stat_client($mac);

    if (property_exists($getid_result[0], "oui")) {
        // this field(manufacturer) seems to exist on valid mac addresses
        if (property_exists($getid_result[0], "name")) {
            // this is the alias field if it has been defined
            $name = $getid_result[0]->name;
        } else {
            $name = $getid_result[0]->hostname;
        }
        print 'blocked ' . $name . PHP_EOL;
    } else {
        print 'ERROR: could not block ' . $mac . PHP_EOL;
        print '       check mac address is valid and part of your network' . PHP_EOL;
    }
}

$logoutresults = $unifi_connection->logout(); // always true regardless of site id

echo 'we are done! : ' . $logoutresults . PHP_EOL;
```

**Comment by malle-pietje** [comment]
Credentials look like this:
```php
$controlleruser     = 'xxxxxxx'; // the user name for access to the UniFi Controller
$controllerpassword = 'yyyyyyyyyy'; // the password for access to the UniFi Controller
$controllerurl      = 'https://unifi.mydomain.com'; // full url to the UniFi Controller, eg. 'https://22.22.11.11:8443'
$controllerversion  = '5.8.30'; // the version of the Controller software, eg. '4.6.6' (must be at least 4.0.0)
```

**Comment by malle-pietje** [comment]
OK, but I was using the new version of the client code. With the current public release I see the looping behavior. Please wait for the new release and then test again.

**Comment by johnluber** [comment]
ok, thank you!  when will the new release come?

**Comment by malle-pietje** [comment]
Hopefully fixed with 1.1.50 (released a few minutes ago).

**Comment by johnluber** [comment]
I'll test and let you know

**Comment by malle-pietje** [comment]
👍

**Comment by malle-pietje** [comment]
Too bad for your kids though if this now works😉

**Comment by johnluber** [comment]
Yes, but they're used to it.  left on their own they will literally play video games the entire day - 15 hours or more.  

I must be doing something though with the install.  Git and php are somewhat new to me.

I need to power on though!

**Comment by johnluber** [comment]
qq, where does the block_list.php script expect the config.php file to be?

**Comment by johnluber** [comment]
ok, so I figured that part out.  But, it's still looping.

Here's what I did.  I rm'd the entire install I had.  And, then re-did the git clone for both browser and client.

So, I'd expect I'd have the latest version at that point.  Is that correct?

**Comment by malle-pietje** [comment]
With that you should have the latest client, the API browser tool still comes with the previous API client version so make sure you're not using one.

**Comment by johnluber** [comment]
So, then do I even need the browser tool?

**Comment by malle-pietje** [comment]
Here it isn't looping at all... Which PHP version are you using?
```bash
$ php -v
```

**Comment by johnluber** [comment]
PHP 7.2.24-0ubuntu0.18.04.3

**Comment by malle-pietje** [comment]
> So, then do I even need the browser tool?

No, unless you want to use to browse the data that is exposed by the API using a web browser. To run your own scripts/code all you need is the PHP API client.

**Comment by johnluber** [comment]
ok, but the scripts reference vendor/autoload.php but I don't see that file in just the client clone

**Comment by malle-pietje** [comment]
When using `git` you need to explicitly point to the `Client.php` file:
https://github.com/Art-of-WiFi/UniFi-API-client#git
The autoloader is a feature provided by `composer`.

**Comment by johnluber** [comment]
Got it!  It's working!

**Comment by malle-pietje** [comment]
Without the looping?

**Comment by johnluber** [comment]
Yes!  I needed to RTFM a bit more.  Substituting Client.php for autoload.php fixed it.

Thank yo so much for your patience and help!  You're awesome!

**Comment by malle-pietje** [comment]
You're welcome, and thanks for making me aware of that error in the logout function.
Hopefully, others will also learn from this😊

**Comment by johnluber** [comment]
:)

**Comment by johnluber** [comment]
Everyone is happy but my kids!
