### ISSUE TITLE
[Question] Is it possible to check Scheduled Upgrades

### ISSUE THREAD

**Issue by OS3DrNick** [Art-of-WiFi/UniFi-API-client#54]
Good afternoon,

Basically this is just a question with the usage of your API. 
I use the API for some simple scripting to get some numbers out of the system,
off line devices etc. 
I spend quite some time lately adding all devices to an Scheduled Upgrade schema, 
but with the change of devices / sites maybe some AP's / switches are not in the upgrade any more.

Is there a way with the API to get 'some' info regarding the scheduled upgrades? 
I searched through the 'Client.php' but was not able to find anything,
the API page https://ubntwiki.com/products/software/unifi-controller/api also didnt note anything.
Also didn't find any info in the response (json) per device,  or maybe i overlooked..

Hope you have some info.

**Comment by malle-pietje** [comment]
AFAIK there are no routes to verify the status of scheduled updates.

Instead, we are working on implementing our own scheduled upgrade engine which works across multiple sites across multiple controllers. This also allows us to perform rolling updates for switches that aren't supported by the UniFi controller.
