### ISSUE TITLE
Xamp ports changing when I do a request

### ISSUE THREAD

**Issue by Bhass99** [Art-of-WiFi/UniFi-API-client#55]
Hi,

When I want to make a request like ($results          = $unifi_connection->list_admins();) then the XAMPP ports keep changing and my website keeps loading and finally crashes...
Do you know how to fix it or do you have an idea where the problem lies?

Thanks in advance.

**Comment by malle-pietje** [comment]
@Bhass99 I'm sorry but I have no clue having never worked with XAMPP myself. Maybe other users of the PHP API client can chip in here?

**Comment by Bhass99** [comment]
I have fixed the issue! the issue was that my site name was wrong.
