### ISSUE TITLE
Only list_sites() returns data, other functions returns "false"

### ISSUE THREAD

**Issue by Bhass99** [Art-of-WiFi/UniFi-API-client#56]
Hi,

I get only data with list_sites(), but if I try other functions it returns "false"...?

**Comment by malle-pietje** [comment]
Without knowing whether you are using the correct site context (https://github.com/Art-of-WiFi/UniFi-API-client#important-notes) I can't tell you why this is happening.

Also, which controller version is this?

**Comment by malle-pietje** [comment]
No feedback provided so closing this issue.
