### ISSUE TITLE
Cannot get device name

### ISSUE THREAD

**Issue by Mandorlo** [Art-of-WiFi/UniFi-API-client#59]
Hi, thank you for providing this API it's very useful. I have a problem retrieving the necessary fields of the device object though. When I use the **list_devices** method, it lists the devices but without the "**name**" field. Could you add the "**name**" field (and possibly other missing fields) in the response ? Or maybe should I retrieve this field by some other mean ?

**Comment by malle-pietje** [comment]
You're welcome. The PHP API doesn't manipulate the output that is returned by the UniFi controller API. That being said, I'm unable to replicate what you're seeing: in our test lab, the controller (version 5.12.66) returns the name attribute for the devices when using `list_devices()` as expected.

Check the API Browser demo where you can the results from the demo controller provided by Ubiquiti:
https://api-browser-demo.artofwifi.net/

If you are still having issues please share the controller version and a sanitized example of a device where you are not seeing the name, even though an alias has been set through the controller UI.

**Comment by Mandorlo** [comment]
My bad, it was an error in my code, everything looks fine now. sorry
