### ISSUE TITLE
Is it possible to change the hostname of an authorized device?

### ISSUE THREAD

**Issue by Buendy** [Art-of-WiFi/UniFi-API-client#60]
Hello!

Would it be possible to change the hostname of an authorized (to be able to see it in the controller) device with the API?

Thanks!

**Comment by malle-pietje** [comment]
Hi, to be specific, you can't change the hostname itself (this is managed by the device itself or through DNS) but you can change the alias which overrides the hostname in most controller views.

IIRC this is the function to use:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L491-L511
