### ISSUE TITLE
Add IP addresses to firewall group

### ISSUE THREAD

**Issue by vespino** [Art-of-WiFi/UniFi-API-client#61]
Is it possible to add IP addresses to firewall groups using the API? I have a group of IP addresses which are blocked from my network. I would like to be able to add addresses to this group automatically based on log files my servers generate throughout the day.

**Comment by malle-pietje** [comment]
Yes, there are several methods/function that allow you to work with firewall groups such as this one:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L1274

**Comment by vespino** [comment]
Thanks @malle-pietje, I will give that a try!

**Comment by vespino** [comment]
Already have it running!

**Comment by malle-pietje** [comment]
Thanks for the feedback!
