### ISSUE TITLE
enable/disable port forwarding

### ISSUE THREAD

**Issue by vespino** [Art-of-WiFi/UniFi-API-client#62]
I have found it's possible to grab a list of port forwardings, but is it possible to enable/disable a port forwarding rule using the API?

**Comment by malle-pietje** [comment]
There aren’t specific functions in the client for this (yet), but you can achieve it by using the custom method. I can check to see what that would roughly look like.

**Comment by malle-pietje** [comment]
When using the `custom_api_request()` method it should be called like so:
```php
custom_api_request('/api/s/YOUR_SITE_ID/rest/portforward', 'POST', $payload, 'array');
```
Here `$payload` must be a PHP associative array that is structured similar to the output from `list_portforwarding()`:
```javascript
    {
        "_id": "5ebd0c38a999c65ac2162e9e",
        "enabled": true,
        "pfwd_interface": "wan",
        "name": "test rule for 2222",
        "dst_port": "2222",
        "fwd": "192.168.0.10",
        "fwd_port": "2221",
        "log": true,
        "src": "any",
        "proto": "tcp_udp",
        "site_id": "558c44fee4b000d0b32a8bbb"
    }
```

**Comment by malle-pietje** [comment]
So if you wish to simply enable/disable one rule temporarily, fetch all rules using `list_portforwarding()`, extract the required rule, modify the *enabled* attribute and push the single rule back using the above example.

**Comment by vespino** [comment]
@malle-pietje thanks again for your response. I walked through your instructions which seem perfectly clear, but nothing is happening. I have looked at the inspector and it seems to PUT to https://unifi.opolo.nl:8443/api/s/**default**/rest/portforward/**site_id** so I tried several combinations but unfortunately without success.

**Comment by vespino** [comment]
Found it: $unifi_connection->custom_api_request('/api/s/**default**/rest/portforward/**['_id']**, '**PUT**', $payload, 'array');

**Comment by malle-pietje** [comment]
Ah OK, I see I forget to test an update of a rule, my example is for the creation of a rule. It must indeed be a PUT and the correct URL structure is:
```
/api/s/default/rest/portforward/[**rule_id**]
```
This assumes you are working with the default site and rule_id is the value for **_id** from the rule you are updating.

**Comment by malle-pietje** [comment]
You beat me to it😉

**Comment by vespino** [comment]
Thanks for pointing me to this method, it will probably open up a lot of possibilities!

**Comment by malle-pietje** [comment]
It does; I added it to allow users to go ahead by themselves without having to wait for me or someone else to push an update for a new specific function/route.
