### ISSUE TITLE
Is there a way to use "where" condition while using list_clients()

### ISSUE THREAD

**Issue by rerizaldywirawan** [Art-of-WiFi/UniFi-API-client#64]
Hi,

I really like this API, it helps me a lot to achieve my task, but there's something fishy for me.

Can we search a specific IP Address or MAC Address?

Thank you

**Comment by malle-pietje** [comment]
I’m afraid not. There are a couple of functions/routes where your can pass a MAC address but in general this isn’t implemented by Ubiquiti. You will have to implement such logic yourself in the code that executes the requests though the API client.

**Comment by rerizaldywirawan** [comment]
Ahhh .. I see, what you suggest was what i did. OK, I guess we can close this now.
