### ISSUE TITLE
Get site total download stat

### ISSUE THREAD

**Issue by alfo** [Art-of-WiFi/UniFi-API-client#65]
<img width="1007" alt="Screenshot 2020-06-11 at 21 41 48" src="https://user-images.githubusercontent.com/1206159/84437691-55ba4d00-ac2d-11ea-9ffe-37c9ba0edb62.png">

Sorry for the dumb question, but for a while I've been trying to find out how to get the total figure (inside the circle) for a little IoT project I've been working on. I've tried `list_dpi_stats()` but that just provides by category (and summing the categories doesn't add up to that total).

Sure I'm missing something simple, would appreciate any help.

**Comment by malle-pietje** [comment]
That isn't a dumb question. I personally do not use/trust the current DPI stats at all (neither from the API nor the controller web UI), but also find them absolutely useless without knowing the timeframe they apply to.

My advice is to determine what intelligence you are trying to get out out of the data, then select a reliable source from the API that supports that.

**Comment by malle-pietje** [comment]
I suggest looking at the gateways stats as returned by `stat_hourly_gateway()` like these from a USG PRO:
```javascript
    {
        "time": 1591351200000,
        "mem": 24,
        "cpu": 11,
        "lan-rx_errors": 0,
        "lan-tx_errors": 0,
        "lan-rx_bytes": 1189621899.1067932,
        "lan-tx_bytes": 224978889.85189718,
        "lan-rx_packets": 996098.4201346389,
        "lan-tx_packets": 432706.9060587515,
        "lan-rx_dropped": 35,
        "lan-tx_dropped": 0,
        "wan-tx_bytes": 1188488097.1787026,
        "wan-rx_bytes": 224811377.05538556,
        "max_rx_bytes-r": 2289898,
        "max_tx_bytes-r": 4819060,
        "wan2-tx_bytes": 0,
        "wan2-rx_bytes": 0,
        "latency_min": 1,
        "latency_avg": 10.020277777777778,
        "latency_max": 13,
        "gw": "44:d9:ee:bb:dd:ff",
        "oid": "44:d9:ee:bb:dd:ff"
    }
```

**Comment by alfo** [comment]
Ah ok, that's more like what I was looking for. Thanks. Is there any way to get the monthly wan-rx_bytes and wan-tx_bytes?

**Comment by malle-pietje** [comment]
You're welcome. Yes, you can generate that yourself by summarizing the results from `stat_daily_gateway()` for the selected range. You may need to expand the attributes to fetch from that route like we did in the API browser here:
https://github.com/Art-of-WiFi/UniFi-API-browser/blob/master/ajax/fetch_collection.php#L33-L59

Passing these attributes will return the output from my sample above.

**Comment by alfo** [comment]
Ok, fantastic. Wow, it's been a long time since I last wrote anything in PHP ahah.
