### ISSUE TITLE
Fast discover client

### ISSUE THREAD

**Issue by un7known** [Art-of-WiFi/UniFi-API-client#67]
How to reduce the time of client discovery at the point?
list_clients($ mac) finds a client after 1-2 minutes.

**Comment by malle-pietje** [comment]
Besides making sure your controller is correctly sized and tuned there's nothing you can do about that. By the way, you will see the same delay through the controller web UI since it also leverages the API for this type of data.

**Comment by un7known** [comment]
in web interface, too, there is a delay. what it means is tuned and sized correctly?

**Comment by malle-pietje** [comment]
No, correct sizing depends on many factors where a badly sized controller will have trouble updating this information. Even still, 1-2 minutes is quite common AFAIK.

**Comment by un7known** [comment]
possible as that to get information more quickly with the most points on the snmp?

**Comment by malle-pietje** [comment]
As I said, not that I know of...
