### ISSUE TITLE
Disable Port On Switch

### ISSUE THREAD

**Issue by christianguei** [Art-of-WiFi/UniFi-API-client#69]
Hello,

First of all, thank you for your amazing work !

I have a 48port switch, i want to be able to call a function (php) to disable a specific port whenever i want.

The finale purpose is to block the internet connexion at the source for specific rooms.

Can you help me ?

Chris

**Comment by christianguei** [comment]
I know that there is the POE_MODE but i a computer is connected to the PORT it will not disable the internet right ?

**Comment by malle-pietje** [comment]
You should be able to re-use a large part of this example:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/update_ac-iw_ports.php

Make sure to pass the correct _id value for the port configuration you wish to apply, especially when re-enabling the port again.

**Comment by christianguei** [comment]
> You should be able to re-use a large part of this example:
> https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/update_ac-iw_ports.php
> 
> Make sure to pass the correct _id value for the port configuration you wish to apply, especially when re-enabling the port again.


Thanks for your quick answer. The problem is that i don't know the parameter to overrirde.

**Comment by malle-pietje** [comment]
Read the code example and the comments carefully, step by step. Also make sure to fetch the port configurations for your site, or use the API Browser tool to get them.

**Comment by malle-pietje** [comment]
For example, one of sites has this port configuration I would apply to disable a switch port:
```
...
    {
        "_id": "558c39fee4b053d0b32a8bb3",
        "site_id": "558c39fee4b053d0b32a8bab",
        "name": "Disabled",
        "forward": "disabled",
        "attr_hidden_id": "Disabled",
        "attr_hidden": true,
        "attr_no_delete": true,
        "attr_no_edit": true
    },
    ...
```

**Comment by christianguei** [comment]
I think that maybe in my case the easiest way would be to apply the "Disabled" profile. Do you have documentation on that ?

**Comment by christianguei** [comment]
Do you see a way to do that ?

**Comment by malle-pietje** [comment]
See the code example I linked to earlier. That explains exactly how to do it.

**Comment by christianguei** [comment]
Hello again,

I tried with this code 

$new_ports_config = [
    'port_overrides' => [
        [
            'port_idx' => 43,
            'portconf_id' => $port_conf_id_port_1,
	    'forward' => 'disabled',
	    'name' => 'Test-Bloc-Port'

        ]
    ]
];

Only the name changes, the LAN port is still enabled.

Do you know the parameter to switch the profile to Disabled instead of All ?

**Comment by malle-pietje** [comment]
Which value did you assign to `$port_conf_id_port_1`? Was that taken from the array that is returned when calling the list_portconf() method/function?

**Comment by christianguei** [comment]
I have the correct value for port_conf_id_port_1. I can see that the name of the correct port (43) changes. I struggle to find the correct parameters to shut down this port.

**Comment by christianguei** [comment]
> 
> 
> Which value did you assign to `$port_conf_id_port_1`? Was that taken from the array that is returned when calling the list_portconf() method/function?

To answer your question, i used the your browser tool to get the value for port_conf_id.

**Comment by malle-pietje** [comment]
> I have the correct value for port_conf_id_port_1. I can see that the name of the correct port (43) changes. I struggle to find the correct parameters to shut down this port.

But is the value the `_id` value of the port configuration named "Disabled"?

**Comment by malle-pietje** [comment]
If it is I'll need to find some time to replicate this and whether anything has changed at the controller end. Which controller version are you using?

**Comment by malle-pietje** [comment]
OK, I will check to see what the solution is.

**Comment by christianguei** [comment]
Here is what i used to answer your question 👍 

<img width="262" alt="Browser" src="https://user-images.githubusercontent.com/71352811/93487347-74ec0900-f905-11ea-9375-f5e51799ecfa.png">

<img width="248" alt="Ubnt" src="https://user-images.githubusercontent.com/71352811/93487411-87664280-f905-11ea-9aa4-22d042b86a0a.png">

And here i past parts of the code i use 👍 
$new_ports_config = [
    'port_overrides' => [
        [
            'port_idx' => 43,
            'portconf_id' => $port_conf_id_port_1,
	    'forward' => 'disabled',
	    'name' => 'Test-Bloc-Port'

        ]
    ]
];

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */

$unifi_connection = new UniFi_API\Client('admin', 'xxxx', 'https://xxxx:8443', $site_id, $controllerversion, false);
$set_debug_mode   = $unifi_connection->set_debug(true);
$loginresults     = $unifi_connection->login();
$data             = $unifi_connection->list_devices($device_mac);
$device_id        = $data[0]->device_id;
$update_device    = $unifi_connection->set_device_settings_base($device_id, $new_ports_config);


if (!$update_device) {
    $error = $unifi_connection->get_last_results_raw();
    echo json_encode($error, JSON_PRETTY_PRINT);
}

/**
 * provide feedback in json format
 */
echo json_encode($update_device, JSON_PRETTY_PRINT);

**Comment by malle-pietje** [comment]
Quick check and here it works. You may need to add this to the payload for the port:
```
...
poe_mode => "auto",
...
```

**Comment by malle-pietje** [comment]
And try what happens when you leave out the key/value pair for `'forward'`, don't think that's needed.

**Comment by christianguei** [comment]
> 
> 
> Quick check and here it works. You may need to add this key/value pair to the payload for the port:
> 
> ```
> ...
> poe_mode => "auto",
> ...
> ```

What key/value did you use to block a port if it works for you ?

**Comment by malle-pietje** [comment]
Need to re-run my test when I have the time...

**Comment by christianguei** [comment]
> 
> 
> Need to re-run my test when I have the time...

Ok i hope you will find a way, your api is top class !

**Comment by christianguei** [comment]
Hello,

Do you have any news ?
Christian

**Comment by malle-pietje** [comment]
I believe I do. With recent controllers you need to pass the entire updated `port_overrides` section. So the flow should be:
- fetch `port_overrides` for the device
- modify and/or extend the `port_overrides` and push these to the controller using the `set_device_settings_base()` method

So the previous approach where you would push a partial `port_overrides` section doesn't work anymore.

**Comment by christianguei** [comment]
> 
> 
> I believe I do. With recent controllers you need to pass the entire updated `port_overrides` section. So the flow should be:
> 
>     * fetch `port_overrides` for the device
> 
>     * modify and/or extend the `port_overrides` and push these to the controller using the `set_device_settings_base()` method
> 
> 
> So the previous approach where you would push a partial `port_overrides` section doesn't work anymore.

Hello,

Thank you for your informations, i've tried (without success) this code 👍 

$new_ports_config = [
    'port_overrides' => [
        [
            'media' =>  'GE',
		'port_idx' => 43,
                'port_poe' =>  true,
                'poe_caps' =>  7,
                'speed_caps' =>  1048623,
                'op_mode' =>  'switch',
                'portconf_id' =>  '57546c0ed4210239e66949d8',
                'poe_mode' =>  'off',
                'autoneg' =>  true,
                'dot1x_mode' =>  'unknown',
                'dot1x_status' =>  'disabled',
                'enable' =>  false,
                'flowctrl_rx' =>  false,
                'flowctrl_tx' =>  false,
                'full_duplex' =>  true,
                'is_uplink' =>  false,
                'jumbo' =>  false,
		'name' =>  'Test-Bloc-Port',
                'masked' =>  false,
                'aggregated_by' =>  false,
		'attr_hidden_id' => 'Disabled',
        	'attr_hidden' => true,
        	'attr_no_delete' => true,
        	'attr_no_edit' => true

        ]
    ]
]; 

Did you managed to make it work ?

**Comment by malle-pietje** [comment]
This code works fine to toggle port 24 (simply comment/uncomment lines as needed):
```php
<?php
/**
 * PHP API usage example
 *
 * contributed by: Art of WiFi
 * description:    example basic PHP script to update the port settings of a UniFi switch
 * note:           requires controller version 5.5.X or higher
 */

/**
 * using the composer autoloader
 */
require_once('vendor/autoload.php');

/**
 * include the config file (place your credentials etc. there if not already present)
 * see the config.template.php file for an example
 */
require_once('config.php');

/**
 * the site to use to log in to the controller
 */
$site_id = 'site_id';

/**
 * the MAC address of the UniFi switch to re-configure
 */
$device_mac = 'ff:cc:aa:77:33:44';

/**
 * port configuration id to apply when disabling the port
 * NOTE: port configurations are available through list_portconf()
 */
$port_conf_id_disabled = '558c39fee4b053d0b32a8bb3';

/**
 * port configuration id to apply when enabling the port
 * NOTE: port configurations are available through list_portconf()
 */
$port_conf_id_enabled = '558c39fee4b053d0b32a8bb2';

/**
 * port index to modify/add
 */
$port_idx = 24;

/**
 * initialize the UniFi API connection class and log in to the controller and do our thing
 */
$unifi_connection   = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion, false);
$set_debug_mode     = $unifi_connection->set_debug(false);
$loginresults       = $unifi_connection->login();
$data               = $unifi_connection->list_devices($device_mac);
$device_id          = $data[0]->device_id;
$existing_overrides = $data[0]->port_overrides;

echo 'original overrides:' . PHP_EOL;
echo json_encode($existing_overrides, JSON_PRETTY_PRINT);

foreach ($existing_overrides as $key => $value) {
    if (!empty($value->port_idx) && $value->port_idx === $port_idx) {
        $new_override = [
            //'portconf_id' => $port_conf_id_disabled,
            'portconf_id' => $port_conf_id_enabled,
            'port_idx'    => $port_idx,
            'poe_mode'    => $value->poe_mode,
            //'name'        => 'Test-Port-Blocked',
            'name'        => 'Test-Port-Unblocked',
        ];

        $existing_overrides[$key] = $new_override;
    }
}

$payload = [
    'port_overrides' => $existing_overrides
];

echo 'payload with updated overrides:' . PHP_EOL;
echo json_encode($payload, JSON_PRETTY_PRINT);

$update_device = $unifi_connection->set_device_settings_base($device_id, $payload);

/**
 * provide feedback in json format
 */
echo json_encode($update_device, JSON_PRETTY_PRINT);
```

**Comment by malle-pietje** [comment]
Closing, please open this issue again if the above code doesn't work for you.

**Comment by christianguei** [comment]
Thank you it worked with the code you gave me !

**Comment by malle-pietje** [comment]
You're welcome. An example based on this code will be added with the next code push.
