### ISSUE TITLE
DHCP Reservations

### ISSUE THREAD

**Issue by jeedee5** [Art-of-WiFi/UniFi-API-client#71]
Hi,

Is it possible to create a client through the API with a fixed ip address? 
We do automated deployments of our servers, with DHCP reservations. I would like to automate the DHCP reservation also. Any idea if this is possible?

In the controller GUI, it would be "Clients - Add Client", and fill in all the details...

**Comment by malle-pietje** [comment]
Yes, with the current built-in methods/functions you can do it as follows:

- create a client using this method:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L400-L435

- then assign an IP address to the newly created client using this method:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L975-L1004

This does require a USG (PRO), UXG PRO, or UDM (PRO).
