### ISSUE TITLE
Bloc, by voucher

### ISSUE THREAD

**Issue by christianguei** [Art-of-WiFi/UniFi-API-client#72]
Hello,

First thanks again for your amazing work. 

Do you have a way to block/unbloc, a voucher ? I have managed to create a voucher, connect with my ipad and now i want to force disconnect my iPad WITHOUT using the MAC address.

I will you this function in a public space and i need to be able to enable/disable a voucher.

**Comment by malle-pietje** [comment]
You're welcome again:wink:

This is not how things work within the UniFi platform. You will have to track down the MAC addresses of devices that used the voucher, roughly like so:
voucher id -> authorization -> client device -> unauthorize
This means you will have to create most of the "surrounding" logic yourself.

**Comment by christianguei** [comment]
Thank you i'll do it like this.
