### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by amerlin** [Art-of-WiFi/UniFi-API-client#73]
Hi, I have a problem retrieving the list of devices, receiving a 401 error. I can log into the system. What can I check?

**Comment by malle-pietje** [comment]
Are you sure you’re using a valid local account and that your login is successful? If this is all correct, please share your code and debug output.

**Comment by amerlin** [comment]
I'm using valid account and the sample code (with username and password changed) . 
What can I check on the devices? 
Thanks

**Comment by malle-pietje** [comment]
Which sample code are you using exactly? Please enable debug using the set_debug() method/function immediately after the instantiation of the class and share the sanitized output you then get.

To see what the data structures look like, please try out our API Browser tool:
https://github.com/Art-of-WiFi/UniFi-API-browser

Demo available here:
https://api-browser-demo.artofwifi.net/

**Comment by malle-pietje** [comment]
Closing due to lack of feedback at this point in time. Feel free to re-open if necessary.
