### ISSUE TITLE
cURL SSL error against controller 5.9.29

### ISSUE THREAD

**Issue by ajweber** [Art-of-WiFi/UniFi-API-client#74]
Testing the list_connected_users.php example, the JSON output is there, but I get this error at the end:
`PHP Notice:  cURL error: OpenSSL SSL_read: Connection was reset, errno 10054 in C:\php\UniFi-API-client-master\src\Client.php on line 279`

Running on Win10 with PHP 7.4.10 for development.  Client.php header indicates v1.1.57

**Comment by malle-pietje** [comment]
I suspect this isn’t related to the API Client class. Can you test what happens when you connect to Ubiquiti's demo controller?
https://demo.ui.com:443
demo/demo
default

**Comment by ajweber** [comment]
Internet demo controller works OK.

What does that leave? SSL Certificates?  (This is using default, "untrusted" UniFi cert.)

**Comment by malle-pietje** [comment]
Googling on the error number leads me to believe this is related to a connectivity issue for example where a firewall resets the connection.

**Comment by ajweber** [comment]
You are right!  My FQDN apparently loops-back through my firewall.  Using the ip address in the URL resolves the error.

Thank you for the quick help!

**Comment by malle-pietje** [comment]
You’re welcome, thanks for confirming!
