### ISSUE TITLE
Just a noob trying to understand this lel

### ISSUE THREAD

**Issue by PsyBooty** [Art-of-WiFi/UniFi-API-client#78]
So firts of all, thx for making this API is rly weird that UBIQUITI dint make this easier;
So im not a developer or PHP God; just a noob that trys to make stuff better at my work;

Soo...  i have a software from my company it's a third party software;
I have access to the mssql db and access to the client name/email other data;
all i want is to get that name and email(this i know how to do on php just a simple select)
and when the user loggin in on the wifi; ask for his email and if the email is in the db let the user use the wifi for some time;

its possible ?
i did saw the example: auth_guest_basic.php;
Is that i need to use?
For the user mac i should use $_SERVER['SERVER_ADDR'] right?
But what about the ap mac? i mean i have like 6 aps; i dont know whitch one the client is in .-.
That is it
any way thx

@Edit;
Another thing... cant we just try to get access to the ubiquit hotspot database and inser the things in ther?

**Comment by malle-pietje** [comment]
The issue list here is meant for support issues directly related to the PHP API client, not for questions about how to build a captive portal. I suggest you create a thread on the Ubiquiti community to see whether someone can pitch in.
