### ISSUE TITLE
Feature request: Enable/Disable Portforward rules

### ISSUE THREAD

**Issue by Tuxos** [Art-of-WiFi/UniFi-API-client#79]
Hi,

first of all, thanks a lot for your great work! I use it for my Homeautomation and it works pretty well :-)

Can you please add a function to enable/disable portforward rules? Or is there a way to do this? I tried a lot with a custom api request, but I don´t get it to work.

Thanks a lot,
Dennis

**Comment by malle-pietje** [comment]
I'll have a look at this as soon as I have a fully functional test network available. But keep in mind, if this can't be achieved using the custom request function/method it also cannot be implemented in the PHP API Client class as a separate function.

**Comment by Tuxos** [comment]
Hi malle-pietje,

thanks for your very fast answer!
I made it work with the custom api call. I had a bad typo :-/ Sorry for that.

It would be great if we can get a own function for this, but I can life also with the custom api call :-)

Kind Regards,
Dennis

**Comment by malle-pietje** [comment]
Cool, thanks for sharing!
