### ISSUE TITLE
cURL error: SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by rainbowhat** [Art-of-WiFi/UniFi-API-client#8]
Any idea , if I can login using http only? 
When visiting on browser , i cant access http

**Comment by rainbowhat** [comment]
$unifi_connection = new \UniFi_API\Client($controller_user, $controller_password, $controller_url, $site_id, $controller_version, false);

Forgot about the true change to false sorry.

**Comment by malle-pietje** [comment]
No problem!
