### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by christianguei** [Art-of-WiFi/UniFi-API-client#80]
Hello,

Is it possible to set a notification everytime a user connect to the Wifi ? Like an e-mail -?

Christian

**Comment by malle-pietje** [comment]
The UniFi controller doesn't have any such support but you could figure out a way to detect new users with a script that polls the API on a regular basis and acts as needed when it identifies one. The UniFi API browser tool will be useful in identifying the best way to detect new users:
https://github.com/Art-of-WiFi/UniFi-API-browser
