### ISSUE TITLE
Best API command/url to retrieve site power ‘ wattage ‘ usage / information ?

### ISSUE THREAD

**Issue by nodecentral** [Art-of-WiFi/UniFi-API-client#85]
Hi,

I’m working my way through the various apis trying to find one that show me the power consumption of all devices on my network, does anyone know the best one to use ?

many thanks

**Comment by nodecentral** [comment]
Found it, there are a number of poe fielded reported from .. local device = 'api/s/default/stat/device'

**Comment by malle-pietje** [comment]
The API Browser tool comes in handy when dealing with questions like these:
https://github.com/Art-of-WiFi/UniFi-API-browser
