### ISSUE TITLE
Issues with Authentication

### ISSUE THREAD

**Issue by wishmedia** [Art-of-WiFi/UniFi-API-client#9]
We have been contracted with building a Guest Portal for a clients Unifi. The portal we have built runs on the "remote server" setting (but the remote server is a local address on the same computer as the AP) and uses a standard web (html, css, apache, mysql, php) environment.

This library accesses the AP and authenticates the MAC Address.

The production Unifi runs on a server and there are about 20(ish) locations that connect to the AP. Currently we are only testing the guest portal on a single location, but this gives you an idea of the setup.

Here is how the process is supposed to go:

1. We require the customer to enter their email address & accept the terms and conditions
2. There is a PHP script using the Unifi API Client that sends a request to the AP to allow the guest
3. We receive a "success" response from the AP
4. We redirect the customers device to a website
5. They now have full access to the wifi.

This works as-expected, maybe 20-30% of the time, the customer is connected fine.

The other 70-80% of the time, at Step 4, after redirecting, the device just refreshes back to the guest authentication page. This happens even though we always receive a "success" response from the AP when trying to authenticate a customers device.

It appears there may be some sort of delay with the AP registering the guest access. I have noticed even when Unauthenticating a user manually from the server it can take up to a minute before the device is asked to authenticate again (I'm not sure if this is related, but it may be).

We have checked all of the networks, connections, etc. and everything appears to be fine. The code appears to be working as-expected as clients eventually log in fine. The issue appears to be between when the authentication is received by the AP and when it actually takes effect.

Is there something we should be doing with the API to fix this issue?

**Comment by malle-pietje** [comment]
I’m afraid this is not an issue with the authentication on the API client side, rather caused by other issues in the communication between your APs and the controller. I suggest you search the UBNT community forum; I have already responded to many similar questions there.

**Comment by malle-pietje** [comment]
Here’s at least one:
https://community.ubnt.com/t5/UniFi-Wireless/Custom-External-Portal-Authorisation-Delay-amp-Loop-v4-8-14/td-p/1510235

And another:
https://community.ubnt.com/t5/UniFi-Wireless/Logging-guest-authorization-per-AP/m-p/1639415

**Comment by wishmedia** [comment]
Sorry! Another question! There are about 200 potential AP's that a person may be connecting to at any given time. How would we determine the AP (and/or Mac Address) that they're trying to connect to?
