### ISSUE TITLE
stat_status() doesn't work anymore on Cloud Key Gen 2

### ISSUE THREAD

**Issue by NebzHB** [Art-of-WiFi/UniFi-API-client#95]
Dear,

it seems there is no /status result on Cloud Key Gen 2 (up to date), if tried manually, there is a redirection to the dashboard.

(don't have the hardware but have been reported by the users of my script using this lib...)

**Comment by malle-pietje** [comment]
I also don’t have a CloudKey that runs the network controller. It’s a pity not all routes are supported on the UniFi OS devices. I will consider adding a list of method/functions not supported with UniFi OS in the README. Modifying these functions to return false on UniFi OS may not be a good idea in case they do get supported over time.
