### ISSUE TITLE
Guest authorize -> session stays in pending state

### ISSUE THREAD

**Issue by arjan-kwikqy** [Art-of-WiFi/UniFi-API-client#96]
Hi,

First of all thank you for this awesome library! 

We have an issue though. When we are authorizing a guest through the 
`$auth_result = $unifi_connection->authorize_guest($mac, $duration, null, null, null, $ap_mac);`
method, the guest session stays at the pending state. Once we manually autorize the pending session in the controller, the guestclient has immediately access to the internet. 

![image](https://user-images.githubusercontent.com/59939962/106865957-2a103980-66cc-11eb-852c-0f8fed279f17.png)

Is there a solution for this? Are we missing something in our script or do we need to change an setting into the controller itself?

Thank you in advance!

Arjan

**Comment by malle-pietje** [comment]
This function/method is the one we use most so I'm quite sure it works in a reliable fashion.

Some questions and suggestions for you:
- which exact controller version are you using?
- which API client version are you using?
- are you sure you're using the correct site id?
- does the authorization request show up in the Events log for the similar to this example?
![Screenshot 2021-02-04 094918](https://user-images.githubusercontent.com/12016131/106867815-54fb8d00-66ce-11eb-916d-18cc00f7e93d.jpg)
- do other API requests such as fetching all devices work?

**Comment by arjan-kwikqy** [comment]
Hi,

We found out that the site ID was not sent properly..! It's working now.

Thank you!

Arjan

**Comment by malle-pietje** [comment]
thanks for the feedback!
