### ISSUE TITLE
MAC address filtering for each port specifically

### ISSUE THREAD

**Issue by NicolasSmit** [Art-of-WiFi/UniFi-API-client#97]
Hi 

Is it possible to manage MAC address filter on each port of a POE, using Art-Of-Wifi library or any API call ?
Reading the documentation, I wasn't able to identify any function able to do that. 

Thanks

**Comment by malle-pietje** [comment]
This can be achieved using the port overrides. The payload for the override to whitelist a MAC address on port 5 would look like this:
```json
      {
         "port_idx":5,
         "portconf_id":"558c39fee4b053d0b32a8bb2",
         "port_security_mac_address":[
            "aa:bb:cc:dd:ee:ff"
         ],
         "port_security_enabled":true
      }
```
You can use this example as a starting point to work with port overrides:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/update_switch_poe-mode.php

**Comment by malle-pietje** [comment]
Obviously, you'll need to pass the payload to the method/function as a PHP associative array... The above JSON format is what the API Client passes on to the respective API route.

**Comment by NicolasSmit** [comment]
Thanks @malle-pietje 👍 
I'm going to give it a try

**Comment by NicolasSmit** [comment]
I used [node-unify](https://github.com/jens-maus/node-unifi) to try this, and it's working great :) 
I suppose this package does the job too

**Comment by malle-pietje** [comment]
Yes, as long as you make sure to pass the correct payload.
