### ISSUE TITLE
Extensibility .. 

### ISSUE THREAD

**Issue by Ericvf** [Art-of-WiFi/UniFi-API-client#98]
I've noticed its hard to extend the Client class. Internally you are leveraging partial classes. But those consuming this package via Nuget have the rely on polymorphism. It would be great to have access to the `ExecuteJsonCommandAsync` method for example. 

That way I can write a derived client class with additional API calls, e.g. `GetEvents` (which is what I needed), without having to clone and compile the library.

**Comment by malle-pietje** [comment]
I have no clue what you are suggesting. If you have ideas for improvements please share some practical examples/content.
